/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pacijent;

import domen.Pacijent;
import gui.enumi.ModForme;
import java.awt.Color;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PacijentDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PacijentDialog.class.getName());

    /**
     * Creates new form PregledDialog
     */
    private Pacijent pacijent;
    private ModForme modForme;
    private java.awt.Frame parent;

    public PacijentDialog(java.awt.Frame parent, boolean modal, Pacijent pacijent, ModForme modForme) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
        this.pacijent = pacijent;
        this.modForme = modForme;
        this.parent = parent;
        obradaModa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPacijenta = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        txtIdPacijenta = new javax.swing.JTextField();
        lblPrezime = new javax.swing.JLabel();
        lblDatumRodjenja = new javax.swing.JLabel();
        lblPol = new javax.swing.JLabel();
        lblMestoRodjenja = new javax.swing.JLabel();
        lblMejl = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JTextField();
        txtMestoRodjenja = new javax.swing.JTextField();
        txtMejl = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        txtIme = new javax.swing.JTextField();
        cmbPol = new javax.swing.JComboBox<>();
        lblDijagnoza = new javax.swing.JLabel();
        cmbDijagnoza = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПАЦИЈЕНТ");

        lblIdPacijenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPacijenta.setText("Ид пацијента :");

        lblIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIme.setText("Име :");

        txtIdPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPacijentaActionPerformed(evt);
            }
        });

        lblPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPrezime.setText("Презиме :");

        lblDatumRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumRodjenja.setText("Датум рођења :");

        lblPol.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPol.setText("Пол :");

        lblMestoRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMestoRodjenja.setText("Место рођења :");

        lblMejl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMejl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMejl.setText("Мејл :");

        txtPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMestoRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMejl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnSacuvaj.setBackground(new java.awt.Color(0, 204, 102));
        btnSacuvaj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvaj.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvaj.setText("САЧУВАЈ ПАЦИЈЕНТА");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setBackground(new java.awt.Color(0, 204, 102));
        btnIzmeni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("ИЗМЕНИ ПАЦИЈЕНТА");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        txtIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cmbPol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "мушки", "женски" }));

        lblDijagnoza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDijagnoza.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDijagnoza.setText("Дијагноза :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDijagnoza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMejl))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMestoRodjenja))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumRodjenja))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPol, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPol, 0, 300, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrezime))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIme))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdPacijenta)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPacijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPacijentaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void obradaModa() {

        if (modForme == ModForme.MOD_KREIRANJE) {
            lblNaslov.setText("КРЕИРАЊЕ ПАЦИЈЕНТА");
            btnIzmeni.setVisible(false);
            lblIdPacijenta.setVisible(false);
            txtIdPacijenta.setVisible(false);

        } else if (modForme == ModForme.MOD_IZMENA) {
            lblNaslov.setText("ИЗМЕНА ПАЦИЈЕНТА");
            btnSacuvaj.setVisible(false);
            lblIdPacijenta.setVisible(false);
            txtIdPacijenta.setVisible(false);

        } else if (modForme == ModForme.MOD_PRIKAZ) {
            lblNaslov.setText("ПРИКАЗ ПАЦИЈЕНТА");
            btnSacuvaj.setVisible(false);
            btnIzmeni.setVisible(false);

            // onemogucavanje polja
            txtIdPacijenta.setEditable(false);
            txtIme.setEditable(false);
            txtPrezime.setEditable(false);
            cmbPol.setEnabled(false);
            txtDatumRodjenja.setVisible(false);
            txtMestoRodjenja.setEditable(false);
            txtMejl.setEditable(false);
            cmbDijagnoza.setEnabled(false);

        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<String> cmbDijagnoza;
    private javax.swing.JComboBox<String> cmbPol;
    private javax.swing.JLabel lblDatumRodjenja;
    private javax.swing.JLabel lblDijagnoza;
    private javax.swing.JLabel lblIdPacijenta;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblMejl;
    private javax.swing.JLabel lblMestoRodjenja;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPol;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtIdPacijenta;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtMejl;
    private javax.swing.JTextField txtMestoRodjenja;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
