/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pacijent;

import domen.Pacijent;
import gui.komponente.ModForme;
import gui.komponente.ModFormePretrazi;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PretragaPacijentaDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PretragaPacijentaDialog.class.getName());

    /**
     * Creates new form KreirajPregledDialog
     */
    private Pacijent pacijent;
    private java.awt.Frame parent;
    private ModFormePretrazi modForme;

    public PretragaPacijentaDialog(java.awt.Frame parent, boolean modal, ModFormePretrazi modForme) {
        super(parent, modal);
        initComponents();
        // postavljanje boje
        getContentPane().setBackground(Color.white);

        this.parent = parent;
        this.modForme = modForme;
        obradaModa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblKrvnaGrupa = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        lblImePrezime = new javax.swing.JLabel();
        cmbKrvnaGrupa = new javax.swing.JComboBox<>();
        txtVrednost = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPacijenti = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕТРАГА ПАЦИЈЕНТА");

        lblKrvnaGrupa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblKrvnaGrupa.setText("Крвна група :");
        lblKrvnaGrupa.setPreferredSize(new java.awt.Dimension(170, 14));

        btnPretrazi.setBackground(new java.awt.Color(0, 204, 102));
        btnPretrazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPretrazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setText("Претражи");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        lblImePrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblImePrezime.setText("Име и презиме :");

        cmbKrvnaGrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "A-", "B-", "AB", "O+", "O-" }));
        cmbKrvnaGrupa.setOpaque(true);
        cmbKrvnaGrupa.setPreferredSize(new java.awt.Dimension(300, 20));
        cmbKrvnaGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKrvnaGrupaActionPerformed(evt);
            }
        });

        txtVrednost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVrednostActionPerformed(evt);
            }
        });

        tblPacijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ид пацијента", "Име", "Презиме", "Пол", "Датум рођења", "Место рођења", "Мејл", "Крвна група"
            }
        ));
        jScrollPane2.setViewportView(tblPacijenti);

        btnIzmeni.setBackground(new java.awt.Color(0, 204, 102));
        btnIzmeni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Измени селектованог пацијента");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setBackground(new java.awt.Color(0, 204, 102));
        btnPrikazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikazi.setText("Прикажи селектованог пацијента");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(0, 204, 102));
        btnObrisi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisi.setText("Обриши селектованог пацијента");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        cmbKrvnaGrupa.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void txtVrednostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVrednostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVrednostActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        int selektovanRed = tblPacijenti.getSelectedRow();
        if (selektovanRed != -1) {
            PacijentDialog dialog = new PacijentDialog(parent, true, pacijent, ModForme.MOD_IZMENA);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали пацијента !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int selektovaniRed = tblPacijenti.getSelectedRow();
        if (selektovaniRed != -1) {
            PacijentDialog dialog = new PacijentDialog(parent, true, pacijent, ModForme.MOD_PRIKAZ);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали пацијента !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void cmbKrvnaGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKrvnaGrupaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKrvnaGrupaActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void obradaModa() {

        if (modForme == ModFormePretrazi.MOD_PRETRAZI_PRIKAZI) {
            lblNaslov.setText("ПРЕТРАГА И ПРИКАЗ ПАЦИЈЕНТА");
            btnIzmeni.setVisible(false);
            btnObrisi.setVisible(false);

        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_IZMENI) {
            lblNaslov.setText("ПРЕТРАГА И ИЗМЕНА ПАЦИЈЕНТА");
            btnPrikazi.setVisible(false);
            btnObrisi.setVisible(false);

        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_OBRISI) {
            lblNaslov.setText("ПРЕТРАГА И БРИСАЊЕ ПАЦИЈЕНТА");
            btnPrikazi.setVisible(false);
            btnIzmeni.setVisible(false);
        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<String> cmbKrvnaGrupa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImePrezime;
    private javax.swing.JLabel lblKrvnaGrupa;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JTable tblPacijenti;
    private javax.swing.JTextField txtVrednost;
    // End of variables declaration//GEN-END:variables
}
