/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import domen.Pacijent;
import domen.Pregled;
import java.awt.Color;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class GlavniFrejm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavniFrejm.class.getName());

    /**
     * Creates new form GlavniFrejm
     */
    public GlavniFrejm() {
        initComponents();

        //izmene boja
        UIManager.put("MenuItem.selectionBackground", new Color(0, 204, 102));
        UIManager.put("Menu.selectionBackground", new Color(0, 204, 102));
        SwingUtilities.updateComponentTreeUI(this);
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblServerska = new javax.swing.JLabel();
        lblNazivSistema = new javax.swing.JLabel();
        btnZaustaviServer = new javax.swing.JButton();
        btnPokreniServer = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        itemBaza = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblServerska.setBackground(new java.awt.Color(255, 255, 255));
        lblServerska.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblServerska.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServerska.setText("Серверска апликација");

        lblNazivSistema.setBackground(new java.awt.Color(255, 255, 255));
        lblNazivSistema.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblNazivSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNazivSistema.setText("СОФТВЕРСКИ СИСТЕМ ЗА ОБАВЉАЊЕ ПРЕГЛЕДА У ЗДРАВСТВЕНОЈ УСТАНОВИ");

        btnZaustaviServer.setBackground(java.awt.Color.red);
        btnZaustaviServer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnZaustaviServer.setForeground(new java.awt.Color(255, 255, 255));
        btnZaustaviServer.setText("Заустави сервер");

        btnPokreniServer.setBackground(new java.awt.Color(102, 255, 102));
        btnPokreniServer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPokreniServer.setForeground(new java.awt.Color(255, 255, 255));
        btnPokreniServer.setText("Покрени сервер");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblServerska, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNazivSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNazivSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblServerska, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(0, 153, 153));
        menuBar.setPreferredSize(new java.awt.Dimension(438, 35));

        itemBaza.setText("База података");

        jMenuItem1.setText("Конфигурација података");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemBaza.add(jMenuItem1);

        menuBar.add(itemBaza);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JMenu itemBaza;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNazivSistema;
    private javax.swing.JLabel lblServerska;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
