/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import domen.Pregled;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class KreirajPregledDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KreirajPregledDialog.class.getName());

    /**
     * Creates new form KreirajPregledDialog
     */
    private Pregled pregled;
    java.awt.Frame parent;

    public KreirajPregledDialog(java.awt.Frame parent, boolean modal, Pregled pregled) {
        super(parent, modal);
        initComponents();
        this.pregled = pregled;
        this.parent = parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPregleda = new javax.swing.JLabel();
        lblLekar = new javax.swing.JLabel();
        btnKreirajPregled = new javax.swing.JButton();
        txtIdPregleda = new javax.swing.JTextField();
        lblPacijent = new javax.swing.JLabel();
        lblDatumVremeKontrole = new javax.swing.JLabel();
        lblDatumVremeZavrsetka = new javax.swing.JLabel();
        lblUkupnoVremeTrajanja = new javax.swing.JLabel();
        lblTerapija = new javax.swing.JLabel();
        cmbLekari = new javax.swing.JComboBox<>();
        cmbPacijenti = new javax.swing.JComboBox<>();
        txtDatumVremeZavrsetka = new javax.swing.JTextField();
        txtDatumVremeKontrole = new javax.swing.JTextField();
        txtDatumVremeTrajanja = new javax.swing.JTextField();
        txtTerapija = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavkePregleda = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnSacuvajPregled = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("КРЕИРАЊЕ ПРЕГЛЕДА");

        lblIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPregleda.setText("Ид прегледа");

        lblLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekar.setText("Лекар :");

        btnKreirajPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnKreirajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKreirajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnKreirajPregled.setText("Креирај преглед");
        btnKreirajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPregledActionPerformed(evt);
            }
        });

        txtIdPregleda.setEnabled(false);
        txtIdPregleda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPregledaActionPerformed(evt);
            }
        });

        lblPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPacijent.setText("Пацијент:");

        lblDatumVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole.setText("Датум и време контроле :");

        lblDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeZavrsetka.setText("Датум и време завршетка :");

        lblUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUkupnoVremeTrajanja.setText("Укупно време трајања:");

        lblTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTerapija.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTerapija.setText("Терапија :");

        cmbLekari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pera Perić", "Mile Milić", "Žika Žikić" }));

        cmbPacijenti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nebojša Ivanović", "Petar Čojbašić", "Milinko Ivanković" }));

        txtDatumVremeTrajanja.setEnabled(false);

        tblStavkePregleda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ид ставке прегледа", "Назив", "Лекарски налаз", "Време трајања", "Дијагноза"
            }
        ));
        jScrollPane2.setViewportView(tblStavkePregleda);

        btnDodajStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnDodajStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDodajStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnDodajStavku.setText("Додај ставку прегледа");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnSacuvajPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnSacuvajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajPregled.setText("САЧУВАЈ ПРЕГЛЕД");
        btnSacuvajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPregledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTerapija))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeTrajanja))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeKontrole))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeZavrsetka))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPacijenti, 0, 1, Short.MAX_VALUE))
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIdPregleda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLekar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbLekari, 0, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKreirajPregled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdPregleda))))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLekari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajPregledActionPerformed

    }//GEN-LAST:event_btnKreirajPregledActionPerformed

    private void txtIdPregledaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPregledaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPregledaActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        // TODO add your handling code here:
        StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent,true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnSacuvajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacuvajPregledActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnKreirajPregled;
    private javax.swing.JButton btnSacuvajPregled;
    private javax.swing.JComboBox<String> cmbLekari;
    private javax.swing.JComboBox<String> cmbPacijenti;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatumVremeKontrole;
    private javax.swing.JLabel lblDatumVremeZavrsetka;
    private javax.swing.JLabel lblIdPregleda;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPacijent;
    private javax.swing.JLabel lblTerapija;
    private javax.swing.JLabel lblUkupnoVremeTrajanja;
    private javax.swing.JTable tblStavkePregleda;
    private javax.swing.JTextField txtDatumVremeKontrole;
    private javax.swing.JTextField txtDatumVremeTrajanja;
    private javax.swing.JTextField txtDatumVremeZavrsetka;
    private javax.swing.JTextField txtIdPregleda;
    private javax.swing.JTextField txtTerapija;
    // End of variables declaration//GEN-END:variables
}
