/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import domen.Pregled;
import domen.StavkaPregleda;
import gui.komponente.ModForme;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PregledDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PregledDialog.class.getName());

    /**
     * Creates new form PregledDialog
     */
    private Pregled pregled;
    private ModForme modForme;
    private java.awt.Frame parent;

    public PregledDialog(java.awt.Frame parent, boolean modal, Pregled pregled, ModForme modForme) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
        this.pregled = pregled;
        this.modForme = modForme;
        this.parent = parent;
        obradaModa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPregleda = new javax.swing.JLabel();
        lblLekar = new javax.swing.JLabel();
        btnKreirajPregled = new javax.swing.JButton();
        txtIdPregleda = new javax.swing.JTextField();
        lblPacijent = new javax.swing.JLabel();
        lblDatumVremeKontrole = new javax.swing.JLabel();
        lblDatumVremeZavrsetka = new javax.swing.JLabel();
        lblUkupnoVremeTrajanja = new javax.swing.JLabel();
        lblTerapija = new javax.swing.JLabel();
        cmbLekari = new javax.swing.JComboBox<>();
        cmbPacijenti = new javax.swing.JComboBox<>();
        txtDatumVremeZavrsetka = new javax.swing.JTextField();
        txtDatumVremeKontrole = new javax.swing.JTextField();
        txtDatumVremeTrajanja = new javax.swing.JTextField();
        txtTerapija = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavkePregleda = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnSacuvajPregled = new javax.swing.JButton();
        btnIzmeniPregled = new javax.swing.JButton();
        btnIzmeniStavku = new javax.swing.JButton();
        btnPrikaziStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕГЛЕД");

        lblIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPregleda.setText("Ид прегледа :");

        lblLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekar.setText("Лекар :");

        btnKreirajPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnKreirajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKreirajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnKreirajPregled.setText("Креирај преглед");
        btnKreirajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPregledActionPerformed(evt);
            }
        });

        txtIdPregleda.setEditable(false);
        txtIdPregleda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPregledaActionPerformed(evt);
            }
        });

        lblPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPacijent.setText("Пацијент :");

        lblDatumVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole.setText("Датум и време контроле :");

        lblDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeZavrsetka.setText("Датум и време завршетка :");

        lblUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUkupnoVremeTrajanja.setText("Укупно време трајања :");

        lblTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTerapija.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTerapija.setText("Терапија :");

        cmbLekari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbLekari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Пера Перић", "Миле Милић", "Живорад Жикић" }));

        cmbPacijenti.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbPacijenti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Небојша Ивановић", "Милош Илић", "Петар Станковић" }));

        txtDatumVremeZavrsetka.setEditable(false);
        txtDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumVremeTrajanja.setEditable(false);
        txtDatumVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tblStavkePregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblStavkePregleda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ид ставке прегледа", "Назив", "Лекарски налаз", "Време трајања", "Дијагноза"
            }
        ));
        tblStavkePregleda.setPreferredSize(new java.awt.Dimension(375, 80));
        tblStavkePregleda.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblStavkePregleda);

        btnDodajStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnDodajStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDodajStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnDodajStavku.setText("Додај ставку прегледа");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnSacuvajPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnSacuvajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajPregled.setText("САЧУВАЈ ПРЕГЛЕД");
        btnSacuvajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPregledActionPerformed(evt);
            }
        });

        btnIzmeniPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnIzmeniPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeniPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeniPregled.setText("ИЗМЕНИ ПРЕГЛЕД");
        btnIzmeniPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPregledActionPerformed(evt);
            }
        });

        btnIzmeniStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnIzmeniStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeniStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeniStavku.setText("Измени селектовану ставку");
        btnIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuActionPerformed(evt);
            }
        });

        btnPrikaziStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnPrikaziStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikaziStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikaziStavku.setText("Прикажи селектовану ставку");
        btnPrikaziStavku.setToolTipText("");
        btnPrikaziStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTerapija))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeTrajanja))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeKontrole))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeZavrsetka))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPacijenti, 0, 1, Short.MAX_VALUE))
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblIdPregleda, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblLekar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbLekari, 0, 400, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKreirajPregled, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdPregleda)))))
                    .addComponent(btnIzmeniPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLekari, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajPregledActionPerformed

    }//GEN-LAST:event_btnKreirajPregledActionPerformed

    private void txtIdPregledaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPregledaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPregledaActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        StavkaPregleda stavka = new StavkaPregleda();
        StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnSacuvajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacuvajPregledActionPerformed

    private void btnIzmeniPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzmeniPregledActionPerformed

    private void btnIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuActionPerformed
        int selektovaniRed = tblStavkePregleda.getSelectedRow();

        if (selektovaniRed != -1) {
            StavkaPregleda stavka = new StavkaPregleda();
            StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnIzmeniStavkuActionPerformed

    private void btnPrikaziStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkuActionPerformed
        int selektovaniRed = tblStavkePregleda.getSelectedRow();

        if (selektovaniRed != -1) {
            StavkaPregleda stavka = new StavkaPregleda();
            StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziStavkuActionPerformed

    private void obradaModa() {

        if (modForme == ModForme.MOD_KREIRANJE) {
            lblNaslov.setText("КРЕИРАЊЕ ПРЕГЛЕДА");
            lblDatumVremeZavrsetka.setVisible(false);
            txtDatumVremeZavrsetka.setVisible(false);

            // sakrivanje dugmeta
            btnIzmeniPregled.setVisible(false);
            btnIzmeniStavku.setVisible(false);
            btnPrikaziStavku.setVisible(false);

        } else if (modForme == ModForme.MOD_IZMENA) {
            lblNaslov.setText("ИЗМЕНА ПРЕГЛЕДА");
            lblDatumVremeZavrsetka.setVisible(false);
            txtDatumVremeZavrsetka.setVisible(false);
            lblIdPregleda.setVisible(false);
            txtIdPregleda.setVisible(false);

            // sakrivanje dugmeta
            btnKreirajPregled.setVisible(false);
            btnSacuvajPregled.setVisible(false);
            btnDodajStavku.setVisible(false);
            btnPrikaziStavku.setVisible(false);

        } else if (modForme == ModForme.MOD_PRIKAZ) {
            lblNaslov.setText("ПРИКАЗ ПРЕГЛЕДА");

            // sakrivanje dugmadi
            btnKreirajPregled.setVisible(false);
            btnSacuvajPregled.setVisible(false);
            btnIzmeniPregled.setVisible(false);
            btnDodajStavku.setVisible(false);
            btnIzmeniStavku.setVisible(false);

            // sakrivanje combo box-a
            cmbPacijenti.setEnabled(false);
            cmbLekari.setEnabled(false);

            // onemogućavanje izmena txtField
            txtIdPregleda.setEditable(false);
            txtDatumVremeKontrole.setEditable(false);
            txtTerapija.setEditable(false);

        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeniPregled;
    private javax.swing.JButton btnIzmeniStavku;
    private javax.swing.JButton btnKreirajPregled;
    private javax.swing.JButton btnPrikaziStavku;
    private javax.swing.JButton btnSacuvajPregled;
    private javax.swing.JComboBox<String> cmbLekari;
    private javax.swing.JComboBox<String> cmbPacijenti;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatumVremeKontrole;
    private javax.swing.JLabel lblDatumVremeZavrsetka;
    private javax.swing.JLabel lblIdPregleda;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPacijent;
    private javax.swing.JLabel lblTerapija;
    private javax.swing.JLabel lblUkupnoVremeTrajanja;
    private javax.swing.JTable tblStavkePregleda;
    private javax.swing.JTextField txtDatumVremeKontrole;
    private javax.swing.JTextField txtDatumVremeTrajanja;
    private javax.swing.JTextField txtDatumVremeZavrsetka;
    private javax.swing.JTextField txtIdPregleda;
    private javax.swing.JTextField txtTerapija;
    // End of variables declaration//GEN-END:variables
}
