/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import domen.Pregled;
import gui.komponente.ModForme;
import gui.komponente.ModFormePretrazi;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PretragaPregledaDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PretragaPregledaDialog.class.getName());

    /**
     * Creates new form KreirajPregledDialog
     */
    private Pregled pregled;
    private java.awt.Frame parent;
    private ModFormePretrazi modForme;

    public PretragaPregledaDialog(java.awt.Frame parent, boolean modal, ModFormePretrazi modForme) {
        super(parent, modal);
        initComponents();
        // postavljanje boje
        getContentPane().setBackground(Color.white);

        this.parent = parent;
        this.modForme = modForme;
        obradaModa();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblKriterijumPretrage = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        lblVrednost = new javax.swing.JLabel();
        cmbKriterijum = new javax.swing.JComboBox<>();
        txtVrednost = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPregledi = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕТРАГА ПРЕГЛЕДА");

        lblKriterijumPretrage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblKriterijumPretrage.setText("Критеријум претраге :");
        lblKriterijumPretrage.setPreferredSize(new java.awt.Dimension(170, 14));

        btnPretrazi.setBackground(new java.awt.Color(0, 153, 153));
        btnPretrazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPretrazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setText("Претражи");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        lblVrednost.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblVrednost.setText("Вредност :");

        cmbKriterijum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Преглед", "Лекар", "Пацијент", "Дијагноза" }));
        cmbKriterijum.setOpaque(true);
        cmbKriterijum.setPreferredSize(new java.awt.Dimension(300, 20));

        txtVrednost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVrednostActionPerformed(evt);
            }
        });

        tblPregledi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ид ставке прегледа", "Лекар", "Пацијент", "Датум и време завршетка", "Датум и време контроле", "Укупно време трајња", "Терапија"
            }
        ));
        jScrollPane2.setViewportView(tblPregledi);

        btnIzmeni.setBackground(new java.awt.Color(0, 153, 153));
        btnIzmeni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Измени селектовани преглед");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setBackground(new java.awt.Color(0, 153, 153));
        btnPrikazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikazi.setText("Прикажи селектовани преглед");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 530, Short.MAX_VALUE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVrednost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        cmbKriterijum.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void txtVrednostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVrednostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVrednostActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        int selektovanRed = tblPregledi.getSelectedRow();
        if (selektovanRed != -1) {
            PregledDialog dialog = new PregledDialog(parent, true, pregled, ModForme.MOD_IZMENA);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали преглед !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int selektovaniRed = tblPregledi.getSelectedRow();
        if (selektovaniRed != -1) {
            PregledDialog dialog = new PregledDialog(parent, true, pregled, ModForme.MOD_PRIKAZ);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали преглед !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    /**
     * @param args the command line arguments
     */
    private void obradaModa() {

        if (modForme == ModFormePretrazi.MOD_PRETRAZI_IZMENI) {
            lblNaslov.setText("ПРЕТРАГА И ИЗМЕНА ПРЕГЛЕДА");
            btnPrikazi.setVisible(false);
        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_PRIKAZI) {
            lblNaslov.setText("ПРЕТРАГА И ПРИКАЗ ПРЕГЛЕДА");
            btnIzmeni.setVisible(false);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<String> cmbKriterijum;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKriterijumPretrage;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblVrednost;
    private javax.swing.JTable tblPregledi;
    private javax.swing.JTextField txtVrednost;
    // End of variables declaration//GEN-END:variables
}
