/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import domen.Pregled;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class StavkaPregledaDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StavkaPregledaDialog.class.getName());

    /**
     * Creates new form KreirajPregledDialog
     */
    private Pregled pregled;

    public StavkaPregledaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.pregled = pregled;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdStavke = new javax.swing.JLabel();
        txtIdStavke = new javax.swing.JTextField();
        lblDijagnoza = new javax.swing.JLabel();
        lblLekarskiNalaz = new javax.swing.JLabel();
        lblNazivStavke = new javax.swing.JLabel();
        lblVremeTrajanja = new javax.swing.JLabel();
        cmbDijagnoze = new javax.swing.JComboBox<>();
        txtNazivStavke = new javax.swing.JTextField();
        txtLekarskiNalaz = new javax.swing.JTextField();
        txtVremeTrajanja = new javax.swing.JTextField();
        btnSacuvajStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ДОДАВАЊЕ СТАВКЕ ПРЕГЛЕДА");

        lblIdStavke.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdStavke.setText("Ид ставке");

        txtIdStavke.setEnabled(false);
        txtIdStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdStavkeActionPerformed(evt);
            }
        });

        lblDijagnoza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDijagnoza.setText("Дијагноза :");

        lblLekarskiNalaz.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekarskiNalaz.setText("Лекарски налаз :");

        lblNazivStavke.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNazivStavke.setText("Назив ставке :");

        lblVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblVremeTrajanja.setText("Време трајања");

        cmbDijagnoze.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prehlada", "Stomačna infekcija", "Glavobolja" }));

        txtVremeTrajanja.setEnabled(false);

        btnSacuvajStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnSacuvajStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvajStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajStavku.setText("Сачувај ставку прегледа");
        btnSacuvajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDijagnoze, 0, 202, Short.MAX_VALUE))
                    .addComponent(btnSacuvajStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblNazivStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(lblLekarskiNalaz, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(lblIdStavke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVremeTrajanja, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtLekarskiNalaz, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNazivStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtIdStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtIdStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIdStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNazivStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekarskiNalaz, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLekarskiNalaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDijagnoze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSacuvajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdStavkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdStavkeActionPerformed

    private void btnSacuvajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajStavkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSacuvajStavkuActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajStavku;
    private javax.swing.JComboBox<String> cmbDijagnoze;
    private javax.swing.JLabel lblDijagnoza;
    private javax.swing.JLabel lblIdStavke;
    private javax.swing.JLabel lblLekarskiNalaz;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNazivStavke;
    private javax.swing.JLabel lblVremeTrajanja;
    private javax.swing.JTextField txtIdStavke;
    private javax.swing.JTextField txtLekarskiNalaz;
    private javax.swing.JTextField txtNazivStavke;
    private javax.swing.JTextField txtVremeTrajanja;
    // End of variables declaration//GEN-END:variables
}
