/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import server.Server;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class GlavniFrejm extends javax.swing.JFrame {

    private String port;
    private String korisnickoIme;
    private String lozinka;
    private Server server;

    /**
     * Creates new form GlavniFrejm
     */
    public GlavniFrejm() {
        initComponents();

        //izmene boja
        UIManager.put("MenuItem.selectionBackground", new Color(0, 204, 102));
        UIManager.put("Menu.selectionBackground", new Color(0, 204, 102));
        SwingUtilities.updateComponentTreeUI(this);
        getContentPane().setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStatus = new javax.swing.JLabel();
        lblNazivSistema = new javax.swing.JLabel();
        btnZaustaviServer = new javax.swing.JButton();
        btnPokreniServer = new javax.swing.JButton();
        lblNazivAplikacije = new javax.swing.JLabel();
        lblStatusVr = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        itemBaza = new javax.swing.JMenu();
        itemKonfiguracija = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblStatus.setText("Статус сервера:");

        lblNazivSistema.setBackground(new java.awt.Color(255, 255, 255));
        lblNazivSistema.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblNazivSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNazivSistema.setText("СОФТВЕРСКИ СИСТЕМ ЗА ОБАВЉАЊЕ ПРЕГЛЕДА У ЗДРАВСТВЕНОЈ УСТАНОВИ");

        btnZaustaviServer.setBackground(java.awt.Color.red);
        btnZaustaviServer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnZaustaviServer.setForeground(new java.awt.Color(255, 255, 255));
        btnZaustaviServer.setText("Заустави сервер");
        btnZaustaviServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviServerActionPerformed(evt);
            }
        });

        btnPokreniServer.setBackground(new java.awt.Color(0, 204, 102));
        btnPokreniServer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPokreniServer.setForeground(new java.awt.Color(255, 255, 255));
        btnPokreniServer.setText("Покрени сервер");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        lblNazivAplikacije.setBackground(new java.awt.Color(255, 255, 255));
        lblNazivAplikacije.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblNazivAplikacije.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNazivAplikacije.setText("Серверска апликација");

        lblStatusVr.setBackground(new java.awt.Color(255, 255, 255));
        lblStatusVr.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblStatusVr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNazivAplikacije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNazivSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatusVr, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNazivSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNazivAplikacije, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btnPokreniServer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnZaustaviServer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusVr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(0, 153, 153));
        menuBar.setPreferredSize(new java.awt.Dimension(438, 50));

        itemBaza.setForeground(new java.awt.Color(255, 255, 255));
        itemBaza.setText("База података");

        itemKonfiguracija.setText("Конфигурација података");
        itemKonfiguracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKonfiguracijaActionPerformed(evt);
            }
        });
        itemBaza.add(itemKonfiguracija);

        menuBar.add(itemBaza);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemKonfiguracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKonfiguracijaActionPerformed
        PodesavanjaDialog dialog = new PodesavanjaDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemKonfiguracijaActionPerformed

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        new Thread(() -> {
            try {
                server = Server.vratiInstancu();

                SwingUtilities.invokeLater(() -> {
                    lblStatusVr.setText("ПОКРЕНУТ");
                });
                // ulaz u beskonačnu petlju
                server.pokreniServer();

            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,
                        "Грешка приликом покретања сервера !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE
                );
            }
        }
        ).start();

    }//GEN-LAST:event_btnPokreniServerActionPerformed

    private void btnZaustaviServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviServerActionPerformed
        try {
            server = Server.vratiInstancu();
            server.zaustaviServer();
            lblStatusVr.setText("ЗУСТАВЉЕН");
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Грешка приликом заустављања сервера !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnZaustaviServerActionPerformed

    private void citanjeKonfiguracije() {
        try {
            BufferedReader bf = new BufferedReader(new FileReader("src/server/konfiguracija.txt"));
            try {
                port = bf.readLine();
                korisnickoIme = bf.readLine();
                lozinka = bf.readLine();
            } catch (IOException ex) {
                System.out.println("gui.GlavniFrejm.citanjeKonfiguracije()");
            }

            System.out.println("ISPIS: " + port + " " + korisnickoIme + " " + lozinka);
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnZaustaviServer;
    private javax.swing.JMenu itemBaza;
    private javax.swing.JMenuItem itemKonfiguracija;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNazivAplikacije;
    private javax.swing.JLabel lblNazivSistema;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusVr;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
