/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PodesavanjaDialog extends javax.swing.JDialog {

    /**
     * Creates new form PregledDialog
     *
     * @param parent
     * @param modal
     */
    JLabel lblStatusVr;

    public PodesavanjaDialog(java.awt.Frame parent, boolean modal, JLabel lblStatusVr) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);

        this.lblStatusVr = lblStatusVr;

        // metode
        popuniPolja();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblBrojPorta = new javax.swing.JLabel();
        lblKorisnickoIme = new javax.swing.JLabel();
        txtBrPorta = new javax.swing.JTextField();
        lblLozinka = new javax.swing.JLabel();
        txtLozinka = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        txtKorisnickoIme = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПОДЕШАВАЊА БАЗЕ ПОДAТАКА");

        lblBrojPorta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBrojPorta.setText("Број порта :");

        lblKorisnickoIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblKorisnickoIme.setText("Корисничко име базе:");

        txtBrPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrPortaActionPerformed(evt);
            }
        });

        lblLozinka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLozinka.setText("Лозинка:");

        txtLozinka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnSacuvaj.setBackground(new java.awt.Color(0, 204, 102));
        btnSacuvaj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvaj.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvaj.setText("САЧУВАЈ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        txtKorisnickoIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLozinka, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtKorisnickoIme))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblBrojPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBrPorta)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBrPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        if (lblStatusVr.getText() == "ПОКРЕНУТ") {
            JOptionPane.showMessageDialog(this, "Не можете мењати конфигурационе  "
                    + "податке док је сервер покренут !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // kreiranje properties
            Properties props = new Properties();
            // dodavanje properties-a
            props.setProperty("brojPorta", txtBrPorta.getText());
            props.setProperty("korisnickoIme", txtKorisnickoIme.getText());
            props.setProperty("lozinka", txtLozinka.getText());

            // kreiranje izlaznog toka
            FileOutputStream fs = new FileOutputStream("src/db/konfig.properties");
            // ubacivanje props-a preko toka
            props.store(fs, null);

            JOptionPane.showMessageDialog(this,
                    "Успешно сачувана подешавања. ",
                    "ОБАВЕШТЕЊЕ",
                    JOptionPane.INFORMATION_MESSAGE
            );
            dispose();

        } catch (HeadlessException | IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Грешка приликом чувања података !",
                    "ГРЕШКА",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void txtBrPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrPortaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void popuniPolja() {
        try {

            Properties props = new Properties();
            // kreiranje toka ka fajlu
            FileReader fr = new FileReader("src/db/konfig.properties");
            props.load(fr);

            txtBrPorta.setText(props.getProperty("brojPorta"));
            txtKorisnickoIme.setText(props.getProperty("korisnickoIme"));
            txtLozinka.setText(props.getProperty("lozinka"));

        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Грешка приликом читања конфигурационог фајла !",
                    "ГРЕШКА",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel lblBrojPorta;
    private javax.swing.JLabel lblKorisnickoIme;
    private javax.swing.JLabel lblLozinka;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JTextField txtBrPorta;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JTextField txtLozinka;
    // End of variables declaration//GEN-END:variables
}
