/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.forme;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class GlavniFrejm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavniFrejm.class.getName());

    /**
     * Creates new form GlavniFrejm
     */
    public GlavniFrejm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuPregled = new javax.swing.JMenu();
        itemKreirajPregled = new javax.swing.JMenuItem();
        itemPretraziPregled = new javax.swing.JMenuItem();
        itemPromeniPregled = new javax.swing.JMenuItem();
        menuPacijent = new javax.swing.JMenu();
        itemKreirajPacijenta = new javax.swing.JMenuItem();
        itemPretraziPacijenta = new javax.swing.JMenuItem();
        itemIzmeniPacijenta = new javax.swing.JMenuItem();
        itemObrisiPacijenta = new javax.swing.JMenuItem();
        menuSpecijalizacija = new javax.swing.JMenu();
        itemUbaciSpecijalizaciju = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Софтверски систем за обављање преглед у здравственој установи");

        menuBar.setPreferredSize(new java.awt.Dimension(438, 35));

        menuPregled.setText("Преглед");

        itemKreirajPregled.setText("Креирај преглед");
        itemKreirajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKreirajPregledActionPerformed(evt);
            }
        });
        menuPregled.add(itemKreirajPregled);

        itemPretraziPregled.setText("Претражи преглед");
        itemPretraziPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPretraziPregledActionPerformed(evt);
            }
        });
        menuPregled.add(itemPretraziPregled);

        itemPromeniPregled.setText("Измени преглед");
        itemPromeniPregled.setToolTipText("");
        itemPromeniPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPromeniPregledActionPerformed(evt);
            }
        });
        menuPregled.add(itemPromeniPregled);

        menuBar.add(menuPregled);

        menuPacijent.setText("Пацијент");

        itemKreirajPacijenta.setText("Креирај пацијента");
        menuPacijent.add(itemKreirajPacijenta);

        itemPretraziPacijenta.setText("Претражи пацијента");
        menuPacijent.add(itemPretraziPacijenta);

        itemIzmeniPacijenta.setText("Измени пацијента");
        itemIzmeniPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIzmeniPacijentaActionPerformed(evt);
            }
        });
        menuPacijent.add(itemIzmeniPacijenta);

        itemObrisiPacijenta.setText("Обриши пацијента");
        menuPacijent.add(itemObrisiPacijenta);

        menuBar.add(menuPacijent);

        menuSpecijalizacija.setText("Специјализација");

        itemUbaciSpecijalizaciju.setText("Убаци специјализацију");
        itemUbaciSpecijalizaciju.setToolTipText("");
        menuSpecijalizacija.add(itemUbaciSpecijalizaciju);

        menuBar.add(menuSpecijalizacija);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemKreirajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKreirajPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemKreirajPregledActionPerformed

    private void itemPretraziPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPretraziPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPretraziPregledActionPerformed

    private void itemPromeniPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPromeniPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPromeniPregledActionPerformed

    private void itemIzmeniPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIzmeniPacijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIzmeniPacijentaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemIzmeniPacijenta;
    private javax.swing.JMenuItem itemKreirajPacijenta;
    private javax.swing.JMenuItem itemKreirajPregled;
    private javax.swing.JMenuItem itemObrisiPacijenta;
    private javax.swing.JMenuItem itemPretraziPacijenta;
    private javax.swing.JMenuItem itemPretraziPregled;
    private javax.swing.JMenuItem itemPromeniPregled;
    private javax.swing.JMenuItem itemUbaciSpecijalizaciju;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPacijent;
    private javax.swing.JMenu menuPregled;
    private javax.swing.JMenu menuSpecijalizacija;
    // End of variables declaration//GEN-END:variables

}
