/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.forme;

import domen.Pregled;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class GlavniFrejm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavniFrejm.class.getName());

    /**
     * Creates new form GlavniFrejm
     */
    public GlavniFrejm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazivSistema = new javax.swing.JLabel();
        lblPrijavljenVr = new javax.swing.JLabel();
        lblPrijavljen = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuPregled = new javax.swing.JMenu();
        itemKreirajPregled = new javax.swing.JMenuItem();
        itemPretraziPregled = new javax.swing.JMenuItem();
        itemPromeniPregled = new javax.swing.JMenuItem();
        menuPacijent = new javax.swing.JMenu();
        itemKreirajPacijenta = new javax.swing.JMenuItem();
        itemPretraziPacijenta = new javax.swing.JMenuItem();
        itemIzmeniPacijenta = new javax.swing.JMenuItem();
        itemObrisiPacijenta = new javax.swing.JMenuItem();
        menuSpecijalizacija = new javax.swing.JMenu();
        itemUbaciSpecijalizaciju = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblNazivSistema.setBackground(new java.awt.Color(0, 153, 153));
        lblNazivSistema.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblNazivSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblNazivSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNazivSistema.setText("Софтверски систем за обављање прегледа у здравственој установи");
        lblNazivSistema.setOpaque(true);

        lblPrijavljenVr.setBackground(new java.awt.Color(255, 255, 255));
        lblPrijavljenVr.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPrijavljenVr.setLabelFor(lblPrijavljen);
        lblPrijavljenVr.setText("Пера Перић");

        lblPrijavljen.setBackground(new java.awt.Color(255, 255, 255));
        lblPrijavljen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrijavljen.setText("Пријављени лекар: ");

        menuBar.setBackground(new java.awt.Color(0, 153, 153));
        menuBar.setPreferredSize(new java.awt.Dimension(438, 35));

        menuPregled.setForeground(new java.awt.Color(255, 255, 255));
        menuPregled.setText("Преглед");

        itemKreirajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemKreirajPregled.setText("Креирај преглед");
        itemKreirajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemKreirajPregledActionPerformed(evt);
            }
        });
        menuPregled.add(itemKreirajPregled);

        itemPretraziPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemPretraziPregled.setText("Претражи преглед");
        itemPretraziPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPretraziPregledActionPerformed(evt);
            }
        });
        menuPregled.add(itemPretraziPregled);

        itemPromeniPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemPromeniPregled.setText("Измени преглед");
        itemPromeniPregled.setToolTipText("");
        itemPromeniPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPromeniPregledActionPerformed(evt);
            }
        });
        menuPregled.add(itemPromeniPregled);

        menuBar.add(menuPregled);

        menuPacijent.setForeground(new java.awt.Color(255, 255, 255));
        menuPacijent.setText("Пацијент");

        itemKreirajPacijenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemKreirajPacijenta.setText("Креирај пацијента");
        menuPacijent.add(itemKreirajPacijenta);

        itemPretraziPacijenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemPretraziPacijenta.setText("Претражи пацијента");
        menuPacijent.add(itemPretraziPacijenta);

        itemIzmeniPacijenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemIzmeniPacijenta.setText("Измени пацијента");
        itemIzmeniPacijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIzmeniPacijentaActionPerformed(evt);
            }
        });
        menuPacijent.add(itemIzmeniPacijenta);

        itemObrisiPacijenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemObrisiPacijenta.setText("Обриши пацијента");
        menuPacijent.add(itemObrisiPacijenta);

        menuBar.add(menuPacijent);

        menuSpecijalizacija.setForeground(new java.awt.Color(255, 255, 255));
        menuSpecijalizacija.setText("Специјализација");

        itemUbaciSpecijalizaciju.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemUbaciSpecijalizaciju.setText("Убаци специјализацију");
        itemUbaciSpecijalizaciju.setToolTipText("");
        menuSpecijalizacija.add(itemUbaciSpecijalizaciju);

        menuBar.add(menuSpecijalizacija);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(lblPrijavljen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblPrijavljenVr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
            .addComponent(lblNazivSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblNazivSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrijavljenVr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrijavljen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemKreirajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemKreirajPregledActionPerformed
        Pregled pregled = new Pregled();
        KreirajPregledDialog dialog = new KreirajPregledDialog(this,true, pregled);
        dialog.setSize(500, 700);
        dialog.setVisible(true);
    }//GEN-LAST:event_itemKreirajPregledActionPerformed

    private void itemPretraziPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPretraziPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPretraziPregledActionPerformed

    private void itemPromeniPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPromeniPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPromeniPregledActionPerformed

    private void itemIzmeniPacijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIzmeniPacijentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIzmeniPacijentaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemIzmeniPacijenta;
    private javax.swing.JMenuItem itemKreirajPacijenta;
    private javax.swing.JMenuItem itemKreirajPregled;
    private javax.swing.JMenuItem itemObrisiPacijenta;
    private javax.swing.JMenuItem itemPretraziPacijenta;
    private javax.swing.JMenuItem itemPretraziPregled;
    private javax.swing.JMenuItem itemPromeniPregled;
    private javax.swing.JMenuItem itemUbaciSpecijalizaciju;
    private javax.swing.JLabel lblNazivSistema;
    private javax.swing.JLabel lblPrijavljen;
    private javax.swing.JLabel lblPrijavljenVr;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuPacijent;
    private javax.swing.JMenu menuPregled;
    private javax.swing.JMenu menuSpecijalizacija;
    // End of variables declaration//GEN-END:variables

}
