/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme;

import domen.Pregled;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class KreirajPregledDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KreirajPregledDialog.class.getName());

    /**
     * Creates new form KreirajPregledDialog
     */
    public KreirajPregledDialog(java.awt.Frame parent, boolean modal, Pregled pregled) {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPregleda = new javax.swing.JLabel();
        lblLekari = new javax.swing.JLabel();
        btnKreirajPregled = new javax.swing.JButton();
        txtIdPregleda = new javax.swing.JTextField();
        lblPacijenti = new javax.swing.JLabel();
        lblDatumVremeKontrole = new javax.swing.JLabel();
        lblDatumVremeZavrsetka = new javax.swing.JLabel();
        lblUkupnoVremeTrajanja = new javax.swing.JLabel();
        lblTerapija = new javax.swing.JLabel();
        cmbLekari = new javax.swing.JComboBox<>();
        cmbPacijenti = new javax.swing.JComboBox<>();
        txtDatumVremeZavrsetka = new javax.swing.JTextField();
        txtDatumVremeKontrole = new javax.swing.JTextField();
        txtDatumVremeTrajanja = new javax.swing.JTextField();
        txtTerapija = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnKreirajPregled1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("КРЕИРАЊЕ ПРЕГЛЕДА");

        lblIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPregleda.setText("Ид прегледа");

        lblLekari.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekari.setText("Лекар :");

        btnKreirajPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnKreirajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKreirajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnKreirajPregled.setText("Креирај преглед");
        btnKreirajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPregledActionPerformed(evt);
            }
        });

        txtIdPregleda.setEnabled(false);
        txtIdPregleda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPregledaActionPerformed(evt);
            }
        });

        lblPacijenti.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPacijenti.setText("Пацијент:");

        lblDatumVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole.setText("Датум и време контроле :");

        lblDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeZavrsetka.setText("Датум и време завршетка :");

        lblUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUkupnoVremeTrajanja.setText("Укупно време трајања:");

        lblTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTerapija.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTerapija.setText("Терапија :");

        cmbLekari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pera Perić", "Mile Milić", "Žika Žikić" }));

        cmbPacijenti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nebojša Ivanović", "Petar Čojbašić", "Milinko Ivanković" }));

        txtDatumVremeTrajanja.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ид ставке прегледа", "Назив", "Лекарски налаз", "Време трајања"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnKreirajPregled1.setBackground(new java.awt.Color(0, 153, 153));
        btnKreirajPregled1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKreirajPregled1.setForeground(new java.awt.Color(255, 255, 255));
        btnKreirajPregled1.setText("Додај ставку прегледа");
        btnKreirajPregled1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPregled1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(btnKreirajPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblIdPregleda, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addComponent(txtIdPregleda))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTerapija))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeTrajanja))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeKontrole))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatumVremeZavrsetka))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPacijenti, 0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblLekari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbLekari, 0, 1, Short.MAX_VALUE))
                    .addComponent(btnKreirajPregled1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekari, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLekari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPacijenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajPregled1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajPregledActionPerformed
        
    }//GEN-LAST:event_btnKreirajPregledActionPerformed

    private void txtIdPregledaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPregledaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPregledaActionPerformed

    private void btnKreirajPregled1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajPregled1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKreirajPregled1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajPregled;
    private javax.swing.JButton btnKreirajPregled1;
    private javax.swing.JComboBox<String> cmbLekari;
    private javax.swing.JComboBox<String> cmbPacijenti;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDatumVremeKontrole;
    private javax.swing.JLabel lblDatumVremeZavrsetka;
    private javax.swing.JLabel lblIdPregleda;
    private javax.swing.JLabel lblLekari;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPacijenti;
    private javax.swing.JLabel lblTerapija;
    private javax.swing.JLabel lblUkupnoVremeTrajanja;
    private javax.swing.JTextField txtDatumVremeKontrole;
    private javax.swing.JTextField txtDatumVremeTrajanja;
    private javax.swing.JTextField txtDatumVremeZavrsetka;
    private javax.swing.JTextField txtIdPregleda;
    private javax.swing.JTextField txtTerapija;
    // End of variables declaration//GEN-END:variables
}
