/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pacijent;

import domen.Pacijent;
import java.awt.Color;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PacijentDialogPrikaz extends javax.swing.JDialog {


    /**
     * Creates new form PregledDialog
     */
    private final Pacijent pacijent;

    public PacijentDialogPrikaz(java.awt.Frame parent, boolean modal, Pacijent pacijent) {
        super(parent, modal);
        initComponents();
        // postavljanje boje
        getContentPane().setBackground(Color.white);
        this.pacijent = pacijent;
        prikazPacijenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPacijenta = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        txtIdPacijenta = new javax.swing.JTextField();
        lblPrezime = new javax.swing.JLabel();
        lblDatumRodjenja = new javax.swing.JLabel();
        lblPol = new javax.swing.JLabel();
        lblMestoRodjenja = new javax.swing.JLabel();
        lblMejl = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JTextField();
        txtMestoRodjenja = new javax.swing.JTextField();
        txtMejl = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        lblKrvnaGrupa = new javax.swing.JLabel();
        txtPol = new javax.swing.JTextField();
        txtKrvnaGrupa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРИКАЗ ПАЦИЈЕНТА");

        lblIdPacijenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPacijenta.setText("Ид пацијента :");

        lblIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIme.setText("Име :");

        txtIdPacijenta.setEditable(false);

        lblPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPrezime.setText("Презиме :");

        lblDatumRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumRodjenja.setText("Датум рођења (дд.мм.гггг) :");

        lblPol.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPol.setText("Пол :");

        lblMestoRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMestoRodjenja.setText("Место рођења :");

        lblMejl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMejl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMejl.setText("Мејл :");

        txtPrezime.setEditable(false);
        txtPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumRodjenja.setEditable(false);
        txtDatumRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMestoRodjenja.setEditable(false);
        txtMestoRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMejl.setEditable(false);
        txtMejl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtIme.setEditable(false);
        txtIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblKrvnaGrupa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblKrvnaGrupa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKrvnaGrupa.setText("Крвна група : ");

        txtPol.setEditable(false);
        txtPol.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtKrvnaGrupa.setEditable(false);
        txtKrvnaGrupa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMejl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdPacijenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtMestoRodjenja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtMejl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKrvnaGrupa, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtPol)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMejl)
                    .addComponent(lblMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        lblIdPacijenta.getAccessibleContext().setAccessibleName("");
        lblIme.getAccessibleContext().setAccessibleName("");
        lblPrezime.getAccessibleContext().setAccessibleName("");
        lblDatumRodjenja.getAccessibleContext().setAccessibleName("");
        lblPol.getAccessibleContext().setAccessibleName("");
        lblMestoRodjenja.getAccessibleContext().setAccessibleName("");
        lblMejl.getAccessibleContext().setAccessibleName("");
        lblKrvnaGrupa.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prikazPacijenta() {

        txtIdPacijenta.setText("" + pacijent.getIdPacijent());
        txtIme.setText(pacijent.getIme());
        txtPrezime.setText(pacijent.getPrezime());
        txtPol.setText(pacijent.getPol().toString());
        txtDatumRodjenja.setText("" + pacijent.getDatumRodjenja());
        txtMestoRodjenja.setText(pacijent.getMestoRodjenja());
        txtMejl.setText(pacijent.getMejl());
        txtKrvnaGrupa.setText(pacijent.getKrvnaGrupa().toString());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDatumRodjenja;
    private javax.swing.JLabel lblIdPacijenta;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblKrvnaGrupa;
    private javax.swing.JLabel lblMejl;
    private javax.swing.JLabel lblMestoRodjenja;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPol;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtIdPacijenta;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKrvnaGrupa;
    private javax.swing.JTextField txtMejl;
    private javax.swing.JTextField txtMestoRodjenja;
    private javax.swing.JTextField txtPol;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
