/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pacijent;

import controller.GuiController;
import domen.KrvnaGrupa;
import domen.Pacijent;
import domen.enumi.Pol;
import gui.enumi.ModForme;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PacijentDialog extends javax.swing.JDialog {


    /**
     * Creates new form PregledDialog
     */
    private final Pacijent pacijentGlobal;
    private final ModForme modForme;

    public PacijentDialog(java.awt.Frame parent, boolean modal, Pacijent pacijent, ModForme modForme) {
        super(parent, modal);
        initComponents();
        // postavljanje boje
        getContentPane().setBackground(Color.WHITE);
        btnIsprazniPolja.setBackground(Color.WHITE);
        cmbKrvnaGrupa.setBackground(Color.WHITE);
        cmbPol.setBackground(Color.WHITE);
        btnObrisi.setBackground(Color.WHITE);

        this.pacijentGlobal = pacijent;
        this.modForme = modForme;
        obradaModa();
        obradaCmbModela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPacijenta = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        txtIdPacijenta = new javax.swing.JTextField();
        lblPrezime = new javax.swing.JLabel();
        lblDatumRodjenja = new javax.swing.JLabel();
        lblPol = new javax.swing.JLabel();
        lblMestoRodjenja = new javax.swing.JLabel();
        lblMejl = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtDatumRodjenja = new javax.swing.JTextField();
        txtMestoRodjenja = new javax.swing.JTextField();
        txtMejl = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        txtIme = new javax.swing.JTextField();
        cmbPol = new javax.swing.JComboBox<>();
        lblKrvnaGrupa = new javax.swing.JLabel();
        cmbKrvnaGrupa = new javax.swing.JComboBox<>();
        btnIsprazniPolja = new javax.swing.JButton();
        btnKreiraj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПАЦИЈЕНТ");

        lblIdPacijenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPacijenta.setText("Ид пацијента :");

        lblIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIme.setText("Име :");

        lblPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPrezime.setText("Презиме :");

        lblDatumRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumRodjenja.setText("Датум рођења (дд.мм.гггг) :");

        lblPol.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPol.setText("Пол :");

        lblMestoRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMestoRodjenja.setText("Место рођења :");

        lblMejl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMejl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMejl.setText("Мејл :");

        txtPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMestoRodjenja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtMejl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnSacuvaj.setBackground(new java.awt.Color(0, 204, 102));
        btnSacuvaj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvaj.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvaj.setText("САЧУВАЈ ПАЦИЈЕНТА");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzmeni.setBackground(new java.awt.Color(0, 204, 102));
        btnIzmeni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("САЧУВАЈ ИЗМЕНЕ");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        txtIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblKrvnaGrupa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblKrvnaGrupa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKrvnaGrupa.setText("Крвна група : ");

        btnIsprazniPolja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIsprazniPolja.setText("ИСПРАЗНИ ПОЉА");
        btnIsprazniPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsprazniPoljaActionPerformed(evt);
            }
        });

        btnKreiraj.setBackground(new java.awt.Color(0, 204, 102));
        btnKreiraj.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKreiraj.setForeground(new java.awt.Color(255, 255, 255));
        btnKreiraj.setText("КРЕИРАЈ ПАЦИЈЕНТА");
        btnKreiraj.setToolTipText("");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(255, 0, 0));
        btnObrisi.setText("Обриши пацијента");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKreiraj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdPacijenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtMestoRodjenja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtMejl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(cmbKrvnaGrupa, javax.swing.GroupLayout.Alignment.TRAILING, 0, 314, Short.MAX_VALUE)))
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(cmbPol, 0, 314, Short.MAX_VALUE)))
                    .addComponent(btnIsprazniPolja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPacijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMestoRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIsprazniPolja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi)
                .addGap(50, 50, 50))
        );

        lblIdPacijenta.getAccessibleContext().setAccessibleName("");
        lblIme.getAccessibleContext().setAccessibleName("");
        lblPrezime.getAccessibleContext().setAccessibleName("");
        lblDatumRodjenja.getAccessibleContext().setAccessibleName("");
        lblPol.getAccessibleContext().setAccessibleName("");
        lblMestoRodjenja.getAccessibleContext().setAccessibleName("");
        lblMejl.getAccessibleContext().setAccessibleName("");
        lblKrvnaGrupa.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        // provera da li su uneta neophodna polja
        if ("".equals(txtIme.getText()) || "".equals(txtPrezime.getText())
                || cmbPol.getSelectedItem() == null || "".equals(txtDatumRodjenja.getText())
                || "".equals(txtMestoRodjenja.getText())
                || cmbKrvnaGrupa.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Нисте попунили неопходна поља! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            Pacijent pacijentPr = new Pacijent();
            pacijentPr.setIdPacijent(Integer.parseInt(txtIdPacijenta.getText()));
            pacijentPr.setIme(txtIme.getText());
            pacijentPr.setPrezime(txtPrezime.getText());
            // datum
            DateTimeFormatter formater = DateTimeFormatter.ofPattern("dd.MM.yyyy");
            pacijentPr.setDatumRodjenja(
                    LocalDate.parse(txtDatumRodjenja.getText(), formater)
            );
            pacijentPr.setMestoRodjenja(txtMestoRodjenja.getText());
            pacijentPr.setMejl(txtMejl.getText());
            pacijentPr.setKrvnaGrupa((KrvnaGrupa) cmbKrvnaGrupa.getSelectedItem());
            pacijentPr.setPol((Pol) cmbPol.getSelectedItem());

            GuiController.vratiInstancu().promeniPacijenta(pacijentPr);
            JOptionPane.showMessageDialog(this, "Систем је запамтио пацијента. ",
                    "ОБАВЕШТЕЊЕ", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да запамти пацијента.",
                    "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        // provera da li su uneta neophodna polja
        if ("".equals(txtIme.getText()) || "".equals(txtPrezime.getText())
                || cmbPol.getSelectedItem() == null || "".equals(txtDatumRodjenja.getText())
                || "".equals(txtMestoRodjenja.getText()) || "".equals(txtMejl.getText())
                || cmbKrvnaGrupa.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Нисте попунили неопходна поља! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // kreiranje pacijenta
        Pacijent pacijentIzmena = new Pacijent();

        // postavljanje vrednosti
        pacijentIzmena.setIdPacijent(pacijentGlobal.getIdPacijent());
        pacijentIzmena.setIme(txtIme.getText());
        pacijentIzmena.setPrezime(txtPrezime.getText());
        // datum
        DateTimeFormatter formater = DateTimeFormatter.ofPattern("dd.MM.yyyy");
        LocalDate datum = LocalDate.parse(txtDatumRodjenja.getText(), formater);
        pacijentIzmena.setDatumRodjenja(datum);

        pacijentIzmena.setMestoRodjenja(txtMestoRodjenja.getText());
        pacijentIzmena.setMejl(txtMejl.getText());
        pacijentIzmena.setKrvnaGrupa((KrvnaGrupa) cmbKrvnaGrupa.getSelectedItem());
        pacijentIzmena.setPol((Pol) cmbPol.getSelectedItem());

        try {
            GuiController.vratiInstancu().promeniPacijenta(pacijentIzmena);
            JOptionPane.showMessageDialog(this, " Систем је запамтио пацијента. ",
                    "ОБАВЕШТЕЊЕ", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да запамти пацијента. ",
                    "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnIsprazniPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsprazniPoljaActionPerformed

        txtIdPacijenta.setText("");
        txtIme.setText("");
        txtPrezime.setText("");
        txtDatumRodjenja.setText("");
        txtMestoRodjenja.setText("");
        txtMejl.setText("");
    }//GEN-LAST:event_btnIsprazniPoljaActionPerformed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        Pacijent pacijent = new Pacijent();
        try {
            Pacijent pacijentRez = GuiController.vratiInstancu().kreirajPacijenta(pacijent);
            txtIdPacijenta.setText("" + pacijentRez.getIdPacijent());
            JOptionPane.showMessageDialog(this, "Систем је креирао пацијента. ", "ГРЕШКА", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Систем не може да креира пацијента. ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        
            UIManager.put("OptionPane.yesButtonText", "Да");
            UIManager.put("OptionPane.noButtonText", "Не");
            int odgovor = JOptionPane.showConfirmDialog(this, "Да ли желите да обришете пацијента ?",
                    "УПИТНИК", JOptionPane.YES_NO_OPTION);
            
            if (odgovor == JOptionPane.YES_OPTION) {

                try {
                    GuiController.vratiInstancu().obrisiPacijenta(pacijentGlobal);
                    JOptionPane.showMessageDialog(this, "Систем је обрисао пацијента. ", "ОБАВЕШТЕЊЕ",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {

                    if (ex instanceof java.sql.SQLException sqlEx && sqlEx.getErrorCode() == 1451) {
                        JOptionPane.showMessageDialog(this, "Не можете обрисати пацијента, "
                                + "постоје прегледи везани за њега !", "ГРЕШКА",
                                JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Систем не може да обрише пацијента. ", "ГРЕШКА",
                                JOptionPane.ERROR_MESSAGE);
                        ex.printStackTrace();
                    }
                }

            }
        
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void obradaModa() {

        if (modForme == ModForme.MOD_KREIRANJE) {
            lblNaslov.setText("КРЕИРАЊЕ ПАЦИЈЕНТА");
            btnIzmeni.setVisible(false);
            txtIdPacijenta.setEditable(false);

        } else if (modForme == ModForme.MOD_IZMENA) {
            lblNaslov.setText("ИЗМЕНА ПАЦИЈЕНТА");
            btnSacuvaj.setVisible(false);
            txtIdPacijenta.setEditable(false);
            prikazPacijenta();

        }

    }

    private void obradaCmbModela() {
        // za pol
        cmbPol.setModel(new DefaultComboBoxModel<>(Pol.values()));

        // za krvnu grupu
        List<KrvnaGrupa> krvneKrupe;
        try {
            krvneKrupe = GuiController.vratiInstancu().vratiSveKrvneGrupe();
            cmbKrvnaGrupa.setModel(new DefaultComboBoxModel<>(krvneKrupe.toArray(new KrvnaGrupa[0])));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања крвних група !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void prikazPacijenta() {

        txtIdPacijenta.setText("" + pacijentGlobal.getIdPacijent());
        txtIme.setText(pacijentGlobal.getIme());
        txtPrezime.setText(pacijentGlobal.getPrezime());
        cmbPol.setSelectedItem("" + pacijentGlobal.getPol());

        // datum
        LocalDate datum = pacijentGlobal.getDatumRodjenja();
        DateTimeFormatter formater = DateTimeFormatter.ofPattern("dd.MM.yyyy");
        txtDatumRodjenja.setText(datum.format(formater));

        txtMestoRodjenja.setText(pacijentGlobal.getMestoRodjenja());
        txtMejl.setText(pacijentGlobal.getMejl());
        cmbKrvnaGrupa.setSelectedItem(pacijentGlobal.getKrvnaGrupa().toString());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIsprazniPolja;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<KrvnaGrupa> cmbKrvnaGrupa;
    private javax.swing.JComboBox<Pol> cmbPol;
    private javax.swing.JLabel lblDatumRodjenja;
    private javax.swing.JLabel lblIdPacijenta;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblKrvnaGrupa;
    private javax.swing.JLabel lblMejl;
    private javax.swing.JLabel lblMestoRodjenja;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPol;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtIdPacijenta;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtMejl;
    private javax.swing.JTextField txtMestoRodjenja;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
