/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pacijent;

import controller.GuiController;
import domen.KrvnaGrupa;
import domen.Pacijent;
import gui.enumi.ModForme;
import gui.enumi.ModFormePretrazi;
import gui.komponente.TblModelPacijent;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PretragaPacijentaDialog extends javax.swing.JDialog {

    /**
     * Creates new form KreirajPregledDialog
     */
    private final java.awt.Frame parent;
    private final ModFormePretrazi modForme;
    private TblModelPacijent tblModel;

    public PretragaPacijentaDialog(java.awt.Frame parent, boolean modal, ModFormePretrazi modForme) {
        super(parent, modal);
        initComponents();
        // postavljanje boje
        getContentPane().setBackground(Color.white);

        this.parent = parent;
        this.modForme = modForme;

        // funkcije
        obradaModa();
        obradaCmbModela();
        obradaTblModela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblKrvnaGrupa = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        lblIme = new javax.swing.JLabel();
        cmbKrvnaGrupa = new javax.swing.JComboBox<>();
        txtPrezime = new javax.swing.JTextField();
        scrTblPacijent = new javax.swing.JScrollPane();
        tblPacijenti = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblPrezime = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕТРАГА ПАЦИЈЕНТА");

        lblKrvnaGrupa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblKrvnaGrupa.setText("Крвна група :");
        lblKrvnaGrupa.setPreferredSize(new java.awt.Dimension(170, 14));

        btnPretrazi.setBackground(new java.awt.Color(0, 204, 102));
        btnPretrazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPretrazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setText("Претражи");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        lblIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIme.setText("Име :");

        cmbKrvnaGrupa.setOpaque(true);
        cmbKrvnaGrupa.setPreferredSize(new java.awt.Dimension(300, 20));

        tblPacijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPacijenti.setMinimumSize(new java.awt.Dimension(160, 80));
        tblPacijenti.setPreferredSize(new java.awt.Dimension(600, 160));
        scrTblPacijent.setViewportView(tblPacijenti);

        btnIzmeni.setBackground(new java.awt.Color(0, 204, 102));
        btnIzmeni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Измени селектованог пацијента");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setBackground(new java.awt.Color(0, 204, 102));
        btnPrikazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikazi.setText("Прикажи селектованог пацијента");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(255, 0, 0));
        btnObrisi.setText("Обриши селектованог пацијента");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPrezime.setText("Презиме :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPrikazi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(lblPrezime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(cmbKrvnaGrupa, 0, 162, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                        .addComponent(scrTblPacijent)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(scrTblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        cmbKrvnaGrupa.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

        //////////////////////////////////////////////////////////////////////
        //   --- USLOVI ---
        Pacijent pacijentKr = new Pacijent();

        if (!txtIme.getText().trim().isEmpty()) {
            pacijentKr.setIme(txtIme.getText().trim());
        }
        if (!txtPrezime.getText().trim().isEmpty()) {
            pacijentKr.setPrezime(txtPrezime.getText().trim());
        }

        KrvnaGrupa kGrupa = (KrvnaGrupa) cmbKrvnaGrupa.getSelectedItem();
        if (kGrupa != null) {
            pacijentKr.setKrvnaGrupa(kGrupa);
        }
        //////////////////////////////////////////////////////////////////////
        try {
            List<Pacijent> pacijenti = GuiController.vratiInstancu().vratiPacijenteUslov(pacijentKr);

            // postavljanje modela tabele
            tblModel = new TblModelPacijent(pacijenti);
            tblPacijenti.setModel(tblModel);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex, "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        int selektovanRed = tblPacijenti.getSelectedRow();
        if (selektovanRed != -1) {
            // uzimanje pacijenta iz modela
            Pacijent pacijent = tblModel.getPacijent(selektovanRed);
            PacijentDialog dialog = new PacijentDialog(parent, true, pacijent, ModForme.MOD_IZMENA);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали пацијента !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int red = tblPacijenti.getSelectedRow();
        if (red != -1) {
            Pacijent pacijent = tblModel.getPacijent(red);
            PacijentDialogPrikaz dialog = new PacijentDialogPrikaz(parent, true, pacijent);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали пацијента !", "УПОЗОРЕЊЕ",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int selektovanRed = tblPacijenti.getSelectedRow();
        if (selektovanRed == -1) {
            JOptionPane.showMessageDialog(this, "Нисте селектовали пацијента !", "УПОЗОРЕЊЕ",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            Pacijent pacijent = tblModel.getPacijent(selektovanRed);
            try {
                GuiController.vratiInstancu().obrisiPacijenta(pacijent);
                JOptionPane.showMessageDialog(this, "Успешно брисање пацијента !", "ОБАВЕШТЕЊЕ",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {

                if (ex instanceof java.sql.SQLException sqlEx && sqlEx.getErrorCode() == 1451) {
                    JOptionPane.showMessageDialog(this, "Не можете обрисати пацијента, "
                            + "постоје прегледи везани за њега !", "ГРЕШКА",
                            JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Грешка приликом брисања пацијента !", "ГРЕШКА",
                            JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            }

        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void obradaModa() {

        if (modForme == ModFormePretrazi.MOD_PRETRAZI_PRIKAZI) {
            lblNaslov.setText("ПРЕТРАГА И ПРИКАЗ ПАЦИЈЕНТА");
            btnIzmeni.setVisible(false);
            btnObrisi.setVisible(false);

        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_IZMENI) {
            lblNaslov.setText("ПРЕТРАГА И ИЗМЕНА ПАЦИЈЕНТА");
            btnPrikazi.setVisible(false);
            btnObrisi.setVisible(false);

        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_OBRISI) {
            lblNaslov.setText("ПРЕТРАГА И БРИСАЊЕ ПАЦИЈЕНТА");
            btnPrikazi.setVisible(false);
            btnIzmeni.setVisible(false);
        }

    }

    private void obradaCmbModela() {
        List<KrvnaGrupa> kGrupe;
        try {
            // vraćanje podataka iz baze
            kGrupe = GuiController.vratiInstancu().vratiSveKrvneGrupe();
            // dodavanje null vrednosti
            kGrupe.add(0, null);
            // pravljenje niza
            KrvnaGrupa[] nizKGrupe = new KrvnaGrupa[kGrupe.size()];
            nizKGrupe = kGrupe.toArray(nizKGrupe);

            DefaultComboBoxModel<KrvnaGrupa> modelKG = new DefaultComboBoxModel<>(nizKGrupe);
            cmbKrvnaGrupa.setModel(modelKG);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања крвних група !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    private void obradaTblModela(){
        tblModel = new TblModelPacijent(new ArrayList<>());
        tblPacijenti.setModel(tblModel);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<KrvnaGrupa> cmbKrvnaGrupa;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblKrvnaGrupa;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JScrollPane scrTblPacijent;
    private javax.swing.JTable tblPacijenti;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
