/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pacijent;

import controller.GuiController;
import domen.KrvnaGrupa;
import domen.ODObjekat;
import domen.Pacijent;
import domen.Pregled;
import gui.enumi.ModForme;
import gui.enumi.ModFormePretrazi;
import gui.komponente.TblModelPacijent;
import gui.komponente.TblModelPregled;
import gui.pomocni.Pomocni;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PretragaPacijentaDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PretragaPacijentaDialog.class.getName());

    /**
     * Creates new form KreirajPregledDialog
     */
    private final java.awt.Frame parent;
    private final ModFormePretrazi modForme;
    private TblModelPacijent model;

    public PretragaPacijentaDialog(java.awt.Frame parent, boolean modal, ModFormePretrazi modForme) {
        super(parent, modal);
        initComponents();
        // postavljanje boje
        getContentPane().setBackground(Color.white);

        this.parent = parent;
        this.modForme = modForme;

        // funkcije
        obradaModa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblKrvnaGrupa = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        lblIme = new javax.swing.JLabel();
        cmbKrvnaGrupa = new javax.swing.JComboBox<>();
        txtPrezime = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPacijenti = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        lblPrezime = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕТРАГА ПАЦИЈЕНТА");

        lblKrvnaGrupa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblKrvnaGrupa.setText("Крвна група :");
        lblKrvnaGrupa.setPreferredSize(new java.awt.Dimension(170, 14));

        btnPretrazi.setBackground(new java.awt.Color(0, 204, 102));
        btnPretrazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPretrazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setText("Претражи");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        lblIme.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIme.setText("Име :");

        cmbKrvnaGrupa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "A-", "B-", "AB", "O+", "O-" }));
        cmbKrvnaGrupa.setOpaque(true);
        cmbKrvnaGrupa.setPreferredSize(new java.awt.Dimension(300, 20));

        tblPacijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ид пацијента", "Име", "Презиме", "Пол", "Датум рођења", "Место рођења", "Мејл", "Крвна група"
            }
        ));
        jScrollPane2.setViewportView(tblPacijenti);

        btnIzmeni.setBackground(new java.awt.Color(0, 204, 102));
        btnIzmeni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Измени селектованог пацијента");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setBackground(new java.awt.Color(0, 204, 102));
        btnPrikazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikazi.setText("Прикажи селектованог пацијента");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnObrisi.setBackground(new java.awt.Color(0, 204, 102));
        btnObrisi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(255, 255, 255));
        btnObrisi.setText("Обриши селектованог пацијента");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        lblPrezime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPrezime.setText("Презиме :");

        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPrikazi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIme, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(lblPrezime)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(cmbKrvnaGrupa, 0, 162, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                        .addComponent(jScrollPane2)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKrvnaGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        cmbKrvnaGrupa.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

        Pacijent pacijentPr = new Pacijent();
        // punjenje pacijenta uslovima
        pacijentPr.setIme(txtIme.getText());
        pacijentPr.setPrezime(txtPrezime.getText());
        pacijentPr.setKrvnaGrupa((KrvnaGrupa) cmbKrvnaGrupa.getSelectedItem());

        try {
            List<ODObjekat> listaObjekata = GuiController.vratiInstancu().vratiUslov(pacijentPr);
            List<Pacijent> pacijenti = new ArrayList<>();

            for (ODObjekat o : listaObjekata) {
                pacijenti.add((Pacijent) o);
            }
            // postavljanje modela tabele
            TblModelPacijent model = new TblModelPacijent(pacijenti);
            tblPacijenti.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex, "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        int selektovanRed = tblPacijenti.getSelectedRow();
        Pacijent pacijent = new Pacijent();
        if (selektovanRed != -1) {
            PacijentDialog dialog = new PacijentDialog(parent, true, pacijent, ModForme.MOD_IZMENA);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали пацијента !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        int red = tblPacijenti.getSelectedRow();
        if (red != -1) {
            Pacijent pacijent = model.getPacijent(red);
            PacijentDialog dialog = new PacijentDialog(parent, true, pacijent, ModForme.MOD_PRIKAZ);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали пацијента !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    private void obradaModa() {

        if (modForme == ModFormePretrazi.MOD_PRETRAZI_PRIKAZI) {
            lblNaslov.setText("ПРЕТРАГА И ПРИКАЗ ПАЦИЈЕНТА");
            btnIzmeni.setVisible(false);
            btnObrisi.setVisible(false);

        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_IZMENI) {
            lblNaslov.setText("ПРЕТРАГА И ИЗМЕНА ПАЦИЈЕНТА");
            btnPrikazi.setVisible(false);
            btnObrisi.setVisible(false);

        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_OBRISI) {
            lblNaslov.setText("ПРЕТРАГА И БРИСАЊЕ ПАЦИЈЕНТА");
            btnPrikazi.setVisible(false);
            btnIzmeni.setVisible(false);
        }

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<String> cmbKrvnaGrupa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblKrvnaGrupa;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JTable tblPacijenti;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
