/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import controller.GuiController;
import domen.Lekar;
import domen.Pacijent;
import domen.Pregled;
import domen.StavkaPregleda;
import gui.enumi.ModForme;
import gui.komponente.TblModelStavkaPregleda;
import gui.pomocni.Pomocni;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PregledDialog extends javax.swing.JDialog {

    /**
     * Creates new form PregledDialog
     */
    private final Pregled pregledGlobal;
    private final ModForme modForme;
    private final java.awt.Frame parent;
    private TblModelStavkaPregleda tblModel;

    public PregledDialog(java.awt.Frame parent, boolean modal, Pregled pregled, ModForme modForme) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
        this.pregledGlobal = pregled;
        this.modForme = modForme;
        this.parent = parent;

        // funkcije
        obradaModa();
        obradaCmbModela();
        obradaTblModela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPregleda = new javax.swing.JLabel();
        lblLekar = new javax.swing.JLabel();
        btnKreirajPregled = new javax.swing.JButton();
        txtIdPregleda = new javax.swing.JTextField();
        lblPacijent = new javax.swing.JLabel();
        lblDatumVremeKontrole = new javax.swing.JLabel();
        lblDatumVremeZavrsetka = new javax.swing.JLabel();
        lblUkupnoVremeTrajanja = new javax.swing.JLabel();
        lblTerapija = new javax.swing.JLabel();
        cmbLekar = new javax.swing.JComboBox<>();
        cmbPacijent = new javax.swing.JComboBox<>();
        txtDatumVremeZavrsetka = new javax.swing.JTextField();
        txtDatumKontrole = new javax.swing.JTextField();
        txtVremeTrajanja = new javax.swing.JTextField();
        txtTerapija = new javax.swing.JTextField();
        scrTblStavke = new javax.swing.JScrollPane();
        tblStavkaPregleda = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnSacuvajPregled = new javax.swing.JButton();
        btnIzmeniPregled = new javax.swing.JButton();
        btnIzmeniStavku = new javax.swing.JButton();
        btnPrikaziStavku = new javax.swing.JButton();
        lblDatumVremeKontrole1 = new javax.swing.JLabel();
        txtVremeKontrole = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕГЛЕД");

        lblIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPregleda.setText("Ид прегледа :");

        lblLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekar.setText("Лекар :");

        btnKreirajPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnKreirajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKreirajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnKreirajPregled.setText("Креирај преглед");
        btnKreirajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPregledActionPerformed(evt);
            }
        });

        txtIdPregleda.setEditable(false);

        lblPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPacijent.setText("Пацијент :");

        lblDatumVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole.setText("Време контроле (чч:мм) :");

        lblDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeZavrsetka.setText("Датум и време завршетка :");

        lblUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUkupnoVremeTrajanja.setText("Укупно време трајања :");

        lblTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTerapija.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTerapija.setText("Терапија :");

        cmbLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cmbPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumVremeZavrsetka.setEditable(false);
        txtDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtVremeTrajanja.setEditable(false);
        txtVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tblStavkaPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblStavkaPregleda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ид ставке прегледа", "Назив", "Лекарски налаз", "Време трајања", "Дијагноза"
            }
        ));
        tblStavkaPregleda.setMinimumSize(new java.awt.Dimension(80, 100));
        tblStavkaPregleda.setSelectionBackground(new java.awt.Color(255, 255, 255));
        scrTblStavke.setViewportView(tblStavkaPregleda);

        btnDodajStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnDodajStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDodajStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnDodajStavku.setText("Додај ставку прегледа");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnSacuvajPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnSacuvajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajPregled.setText("САЧУВАЈ ПРЕГЛЕД");
        btnSacuvajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPregledActionPerformed(evt);
            }
        });

        btnIzmeniPregled.setBackground(new java.awt.Color(0, 153, 153));
        btnIzmeniPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeniPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeniPregled.setText("ИЗМЕНИ ПРЕГЛЕД");
        btnIzmeniPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniPregledActionPerformed(evt);
            }
        });

        btnIzmeniStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnIzmeniStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeniStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeniStavku.setText("Измени селектовану ставку");
        btnIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuActionPerformed(evt);
            }
        });

        btnPrikaziStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnPrikaziStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikaziStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikaziStavku.setText("Прикажи селектовану ставку");
        btnPrikaziStavku.setToolTipText("");
        btnPrikaziStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkuActionPerformed(evt);
            }
        });

        lblDatumVremeKontrole1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole1.setText("Датум контроле (дд.мм.гггг) :");

        txtVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrTblStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeniPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDatumVremeKontrole1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPacijent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTerapija, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVremeTrajanja)
                            .addComponent(txtVremeKontrole)
                            .addComponent(txtDatumKontrole)
                            .addComponent(txtDatumVremeZavrsetka)
                            .addComponent(cmbPacijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTerapija, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIdPregleda, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(lblLekar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLekar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKreirajPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdPregleda, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajPregled)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumVremeKontrole1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(scrTblStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        lblIdPregleda.getAccessibleContext().setAccessibleName("200");
        lblLekar.getAccessibleContext().setAccessibleName("200");
        lblPacijent.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeKontrole.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeZavrsetka.getAccessibleContext().setAccessibleName("200");
        lblUkupnoVremeTrajanja.getAccessibleContext().setAccessibleName("200");
        lblTerapija.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeKontrole1.getAccessibleContext().setAccessibleName("200");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajPregledActionPerformed

        try {
            Pregled pregledRez = (Pregled) GuiController.vratiInstancu().kreirajPregled(new Pregled());
            if (pregledRez != null) {
                txtIdPregleda.setText("" + pregledRez.getIdPregled());
                JOptionPane.showMessageDialog(this, "Успешно креиран Ид прегледа !",
                        "ОБАВЕШТЕЊЕ", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnKreirajPregledActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed

        StavkaPregleda stavka = new StavkaPregleda();

        // prikaz dialoga za stavku
        StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme, tblModel);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // ispis dimenzija
        int visinaReda = tblStavkaPregleda.getRowHeight();
        System.out.println("Visina reda: " + visinaReda);
        int visinaHedera = tblStavkaPregleda.getTableHeader().getHeight();
        System.out.println("Visina hedera: " + visinaHedera);


    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnSacuvajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPregledActionPerformed

        // provera da li su uneta neophodna polja
        if ("".equals(txtIdPregleda.getText()) || cmbLekar.getSelectedItem() == null
                || cmbPacijent.getSelectedItem() == null || "".equals(txtTerapija.getText())) {
            JOptionPane.showMessageDialog(this, "Нисте попунили неопходна поља! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tblStavkaPregleda.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Немате ниједну ставку прегледа ! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // pokretanje izmene (update) koja je deo SK:Kreiraj pregled
        try {
            Pregled pregled = new Pregled();

            pregled.setIdPregled(Integer.parseInt(txtIdPregleda.getText()));
            pregled.setLekar((Lekar) cmbLekar.getSelectedItem());
            pregled.setPacijent((Pacijent) cmbPacijent.getSelectedItem());
            pregled.setDatumVremeZavrsetka(LocalDateTime.now());

            // datum i vreme
            DateTimeFormatter formaterDatum = DateTimeFormatter.ofPattern("dd.MM.yyyy['.']");
            DateTimeFormatter formaterVreme = DateTimeFormatter.ofPattern("HH:mm");
            LocalDate datum = LocalDate.parse(txtDatumKontrole.getText());
            LocalTime vreme = LocalTime.parse(txtVremeKontrole.getText());
            LocalDateTime datumVremeKontrole = LocalDateTime.of(datum, vreme);
            pregled.setDatumVremeKontrole(datumVremeKontrole);
            pregled.setTerapija(txtTerapija.getText());

            GuiController.vratiInstancu().promeniPregled(pregled);
        } catch (Exception ex) {
            System.getLogger(PregledDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_btnSacuvajPregledActionPerformed

    private void btnIzmeniPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniPregledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzmeniPregledActionPerformed

    private void btnIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuActionPerformed
        int selektovaniRed = tblStavkaPregleda.getSelectedRow();

        if (selektovaniRed != -1) {
            StavkaPregleda stavka = new StavkaPregleda();
            StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme, tblModel);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnIzmeniStavkuActionPerformed

    private void btnPrikaziStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkuActionPerformed
        int selektovaniRed = tblStavkaPregleda.getSelectedRow();

        if (selektovaniRed != -1) {
            StavkaPregleda stavka = new StavkaPregleda();
            StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme, tblModel);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziStavkuActionPerformed

    private void obradaModa() {

        if (modForme == ModForme.MOD_KREIRANJE) {
            lblNaslov.setText("КРЕИРАЊЕ ПРЕГЛЕДА");
            lblDatumVremeZavrsetka.setVisible(false);
            txtDatumVremeZavrsetka.setVisible(false);

            // sakrivanje dugmeta
            btnIzmeniPregled.setVisible(false);
            btnIzmeniStavku.setVisible(false);
            btnPrikaziStavku.setVisible(false);

        } else if (modForme == ModForme.MOD_IZMENA) {
            lblNaslov.setText("ИЗМЕНА ПРЕГЛЕДА");
            lblDatumVremeZavrsetka.setVisible(false);
            txtDatumVremeZavrsetka.setVisible(false);
            lblIdPregleda.setVisible(false);
            txtIdPregleda.setVisible(false);

            // sakrivanje dugmeta
            btnKreirajPregled.setVisible(false);
            btnSacuvajPregled.setVisible(false);
            btnDodajStavku.setVisible(false);
            btnPrikaziStavku.setVisible(false);

        } else if (modForme == ModForme.MOD_PRIKAZ) {
            lblNaslov.setText("ПРИКАЗ ПРЕГЛЕДА");

            // sakrivanje dugmadi
            btnKreirajPregled.setVisible(false);
            btnSacuvajPregled.setVisible(false);
            btnIzmeniPregled.setVisible(false);
            btnDodajStavku.setVisible(false);
            btnIzmeniStavku.setVisible(false);

            // sakrivanje combo box-a
            cmbPacijent.setEnabled(false);
            cmbLekar.setEnabled(false);

            // prikaz
            prikazPregleda();

            // onemogućavanje izmena txtField
            txtIdPregleda.setEditable(false);
            txtDatumKontrole.setEditable(false);
            txtTerapija.setEditable(false);

        }

    }

    private void obradaCmbModela() {
        // za pacijenta
        List<Pacijent> pacijenti = Pomocni.vratiPacijente();
        Pacijent[] nizPacijenti = new Pacijent[pacijenti.size()];
        nizPacijenti = pacijenti.toArray(nizPacijenti);
        DefaultComboBoxModel<Pacijent> modelP = new DefaultComboBoxModel<>(nizPacijenti);
        cmbPacijent.setModel(modelP);

        // za lekara
        List<Lekar> lekari = Pomocni.vratiLekare();
        Lekar[] nizLekari = new Lekar[lekari.size()];
        nizLekari = lekari.toArray(nizLekari);
        DefaultComboBoxModel<Lekar> modelL = new DefaultComboBoxModel<>(nizLekari);
        cmbLekar.setModel(modelL);

    }

    private void obradaTblModela() {

        //List<StavkaPregleda> stavke = Pomocni.vratiStavke();
        tblModel = new TblModelStavkaPregleda(new ArrayList());
        tblStavkaPregleda.setModel(tblModel);
    }

    private void prikazPregleda() {
        txtIdPregleda.setText("" + pregledGlobal.getIdPregled());
        cmbLekar.setSelectedItem(pregledGlobal.getLekar());
        cmbPacijent.setSelectedItem(pregledGlobal.getPacijent());
        txtDatumVremeZavrsetka.setText("" + pregledGlobal.getDatumVremeZavrsetka());
        txtDatumKontrole.setText("" + pregledGlobal.getDatumVremeKontrole());
        txtVremeTrajanja.setText("" + pregledGlobal.getUkupnoVremeTrajanja());
        txtTerapija.setText(pregledGlobal.getTerapija());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeniPregled;
    private javax.swing.JButton btnIzmeniStavku;
    private javax.swing.JButton btnKreirajPregled;
    private javax.swing.JButton btnPrikaziStavku;
    private javax.swing.JButton btnSacuvajPregled;
    private javax.swing.JComboBox<Lekar> cmbLekar;
    private javax.swing.JComboBox<Pacijent> cmbPacijent;
    private javax.swing.JLabel lblDatumVremeKontrole;
    private javax.swing.JLabel lblDatumVremeKontrole1;
    private javax.swing.JLabel lblDatumVremeZavrsetka;
    private javax.swing.JLabel lblIdPregleda;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPacijent;
    private javax.swing.JLabel lblTerapija;
    private javax.swing.JLabel lblUkupnoVremeTrajanja;
    private javax.swing.JScrollPane scrTblStavke;
    private javax.swing.JTable tblStavkaPregleda;
    private javax.swing.JTextField txtDatumKontrole;
    private javax.swing.JTextField txtDatumVremeZavrsetka;
    private javax.swing.JTextField txtIdPregleda;
    private javax.swing.JTextField txtTerapija;
    private javax.swing.JTextField txtVremeKontrole;
    private javax.swing.JTextField txtVremeTrajanja;
    // End of variables declaration//GEN-END:variables
}
