/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import controller.GuiController;
import domen.Pregled;
import domen.StavkaPregleda;
import gui.enumi.ModForme;
import gui.komponente.TblModelStavkaPregleda;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PregledDialogPrikaz extends javax.swing.JDialog {

    /**
     * Creates new form PregledDialog
     */
    private final Pregled pregled;
    private final ModForme modForme;
    private final java.awt.Frame parent;
    private TblModelStavkaPregleda tblModel;

    public PregledDialogPrikaz(java.awt.Frame parent, boolean modal, Pregled pregled, ModForme modForme) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
        this.pregled = pregled;
        this.modForme = modForme;
        this.parent = parent;

        // funkcije
        prikazPregleda();
        ucitajStavke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPregleda = new javax.swing.JLabel();
        lblLekar = new javax.swing.JLabel();
        txtIdPregleda = new javax.swing.JTextField();
        lblPacijent = new javax.swing.JLabel();
        lblDatumVremeKontrole = new javax.swing.JLabel();
        lblDatumVremeZavrsetka = new javax.swing.JLabel();
        lblUkupnoVremeTrajanja = new javax.swing.JLabel();
        lblTerapija = new javax.swing.JLabel();
        txtDatumVremeZavrsetka = new javax.swing.JTextField();
        txtDatumKontrole = new javax.swing.JTextField();
        txtUkupnoVremeTrajanja = new javax.swing.JTextField();
        txtTerapija = new javax.swing.JTextField();
        scrTblStavke = new javax.swing.JScrollPane();
        tblStavkaPregleda = new javax.swing.JTable();
        btnPrikaziStavku = new javax.swing.JButton();
        lblDatumVremeKontrole1 = new javax.swing.JLabel();
        txtVremeKontrole = new javax.swing.JTextField();
        txtLekar = new javax.swing.JTextField();
        txtPacijent = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРИКАЗ ПРЕГЛЕДА");

        lblIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPregleda.setText("Ид прегледа :");

        lblLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekar.setText("Лекар :");

        txtIdPregleda.setEditable(false);

        lblPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPacijent.setText("Пацијент :");

        lblDatumVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole.setText("Време контроле (чч:мм) :");

        lblDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeZavrsetka.setText("Датум и време завршетка :");

        lblUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUkupnoVremeTrajanja.setText("Укупно време трајања :");

        lblTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTerapija.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTerapija.setText("Терапија :");

        txtDatumVremeZavrsetka.setEditable(false);
        txtDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumKontrole.setEditable(false);
        txtDatumKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtUkupnoVremeTrajanja.setEditable(false);
        txtUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTerapija.setEditable(false);
        txtTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tblStavkaPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblStavkaPregleda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ид ставке прегледа", "Назив", "Лекарски налаз", "Време трајања", "Дијагноза"
            }
        ));
        tblStavkaPregleda.setMinimumSize(new java.awt.Dimension(80, 100));
        tblStavkaPregleda.setSelectionBackground(new java.awt.Color(255, 255, 255));
        scrTblStavke.setViewportView(tblStavkaPregleda);

        btnPrikaziStavku.setBackground(new java.awt.Color(0, 204, 102));
        btnPrikaziStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikaziStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikaziStavku.setText("Прикажи селектовану ставку");
        btnPrikaziStavku.setToolTipText("");
        btnPrikaziStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkuActionPerformed(evt);
            }
        });

        lblDatumVremeKontrole1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole1.setText("Датум контроле (дд.мм.гггг) :");

        txtVremeKontrole.setEditable(false);
        txtVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtLekar.setEditable(false);

        txtPacijent.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDatumVremeKontrole1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPacijent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTerapija, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPacijent, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtDatumKontrole)
                            .addComponent(txtVremeKontrole)
                            .addComponent(txtUkupnoVremeTrajanja)
                            .addComponent(txtTerapija)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLekar)
                            .addComponent(txtIdPregleda)))
                    .addComponent(scrTblStavke))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumVremeKontrole1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(scrTblStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        lblIdPregleda.getAccessibleContext().setAccessibleName("200");
        lblLekar.getAccessibleContext().setAccessibleName("200");
        lblPacijent.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeKontrole.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeZavrsetka.getAccessibleContext().setAccessibleName("200");
        lblUkupnoVremeTrajanja.getAccessibleContext().setAccessibleName("200");
        lblTerapija.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeKontrole1.getAccessibleContext().setAccessibleName("200");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkuActionPerformed
        int selektovaniRed = tblStavkaPregleda.getSelectedRow();

        if (selektovaniRed != -1) {
            StavkaPregleda stavka = new StavkaPregleda();
            StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme, tblModel);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziStavkuActionPerformed

    

    private void prikazPregleda() {

        txtIdPregleda.setText("" + pregled.getIdPregled());
        txtLekar.setText(pregled.getLekar().vratiImePrezime());
        txtPacijent.setText(pregled.getPacijent().vratiImePrezime());
        txtDatumVremeZavrsetka.setText("" + pregled.getDatumVremeZavrsetka());
        // datum i vreme kontrole
        txtDatumKontrole.setText("" + pregled.getDatumKontrole());
        txtVremeKontrole.setText("" + pregled.getVremeKontrole());

        txtUkupnoVremeTrajanja.setText("" + pregled.getUkupnoVremeTrajanja());
        txtTerapija.setText(pregled.getTerapija());
    }

    private void ucitajStavke() {

        List<StavkaPregleda> stavke;
        try {
            stavke = GuiController.vratiInstancu().vratiSveStavke(pregled);
            tblModel = new TblModelStavkaPregleda(stavke);
            tblStavkaPregleda.setModel(tblModel);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања ставки !",
                    "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrikaziStavku;
    private javax.swing.JLabel lblDatumVremeKontrole;
    private javax.swing.JLabel lblDatumVremeKontrole1;
    private javax.swing.JLabel lblDatumVremeZavrsetka;
    private javax.swing.JLabel lblIdPregleda;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPacijent;
    private javax.swing.JLabel lblTerapija;
    private javax.swing.JLabel lblUkupnoVremeTrajanja;
    private javax.swing.JScrollPane scrTblStavke;
    private javax.swing.JTable tblStavkaPregleda;
    private javax.swing.JTextField txtDatumKontrole;
    private javax.swing.JTextField txtDatumVremeZavrsetka;
    private javax.swing.JTextField txtIdPregleda;
    private javax.swing.JTextField txtLekar;
    private javax.swing.JTextField txtPacijent;
    private javax.swing.JTextField txtTerapija;
    private javax.swing.JTextField txtUkupnoVremeTrajanja;
    private javax.swing.JTextField txtVremeKontrole;
    // End of variables declaration//GEN-END:variables
}
