/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import controller.GuiController;
import domen.Lekar;
import domen.Pacijent;
import domen.Pregled;
import domen.StavkaPregleda;
import gui.enumi.ModForme;
import gui.komponente.TblModelStavkaPregleda;
import java.awt.Color;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PregledDialog extends javax.swing.JDialog {

    /**
     * Creates new form PregledDialog
     */
    private final Pregled pregledGlobal;
    private final ModForme modForme;
    private final java.awt.Frame parent;
    private TblModelStavkaPregleda tblModel;

    public PregledDialog(java.awt.Frame parent, boolean modal, Pregled pregled, ModForme modForme) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
        this.pregledGlobal = pregled;
        this.modForme = modForme;
        this.parent = parent;
        
        // boja dugmeta
        btnObrisiStavku.setBackground(Color.WHITE);

        // funkcije
        obradaCmbModela();
        obradaModa();
        ucitajStavke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblIdPregleda = new javax.swing.JLabel();
        lblLekar = new javax.swing.JLabel();
        btnKreirajPregled = new javax.swing.JButton();
        txtIdPregleda = new javax.swing.JTextField();
        lblPacijent = new javax.swing.JLabel();
        lblDatumVremeKontrole = new javax.swing.JLabel();
        lblDatumVremeZavrsetka = new javax.swing.JLabel();
        lblUkupnoVremeTrajanja = new javax.swing.JLabel();
        lblTerapija = new javax.swing.JLabel();
        cmbLekar = new javax.swing.JComboBox<>();
        cmbPacijent = new javax.swing.JComboBox<>();
        txtDatumVremeZavrsetka = new javax.swing.JTextField();
        txtDatumKontrole = new javax.swing.JTextField();
        txtUkupnoVremeTrajanja = new javax.swing.JTextField();
        txtTerapija = new javax.swing.JTextField();
        scrTblStavke = new javax.swing.JScrollPane();
        tblStavkaPregleda = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnSacuvajPregled = new javax.swing.JButton();
        btnSacuvajIzmene = new javax.swing.JButton();
        btnIzmeniStavku = new javax.swing.JButton();
        btnPrikaziStavku = new javax.swing.JButton();
        lblDatumVremeKontrole1 = new javax.swing.JLabel();
        txtVremeKontrole = new javax.swing.JTextField();
        btnObrisiStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕГЛЕД");

        lblIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPregleda.setText("Ид прегледа :");

        lblLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekar.setText("Лекар :");

        btnKreirajPregled.setBackground(new java.awt.Color(0, 204, 102));
        btnKreirajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnKreirajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnKreirajPregled.setText("Креирај преглед");
        btnKreirajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajPregledActionPerformed(evt);
            }
        });

        txtIdPregleda.setEditable(false);

        lblPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPacijent.setText("Пацијент :");

        lblDatumVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole.setText("Време контроле (чч:мм) :");

        lblDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeZavrsetka.setText("Датум и време завршетка :");

        lblUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUkupnoVremeTrajanja.setText("Укупно време трајања :");

        lblTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTerapija.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTerapija.setText("Терапија :");

        cmbLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cmbPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumVremeZavrsetka.setEditable(false);
        txtDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDatumKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtUkupnoVremeTrajanja.setEditable(false);
        txtUkupnoVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTerapija.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        tblStavkaPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblStavkaPregleda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblStavkaPregleda.setMinimumSize(new java.awt.Dimension(80, 100));
        tblStavkaPregleda.setSelectionBackground(new java.awt.Color(255, 255, 255));
        scrTblStavke.setViewportView(tblStavkaPregleda);

        btnDodajStavku.setBackground(new java.awt.Color(0, 204, 102));
        btnDodajStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDodajStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnDodajStavku.setText("Додај ставку прегледа");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnSacuvajPregled.setBackground(new java.awt.Color(0, 204, 102));
        btnSacuvajPregled.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvajPregled.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajPregled.setText("САЧУВАЈ ПРЕГЛЕД");
        btnSacuvajPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajPregledActionPerformed(evt);
            }
        });

        btnSacuvajIzmene.setBackground(new java.awt.Color(0, 204, 102));
        btnSacuvajIzmene.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvajIzmene.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajIzmene.setText("САЧУВАЈ ИЗМЕНЕ");
        btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIzmeneActionPerformed(evt);
            }
        });

        btnIzmeniStavku.setBackground(new java.awt.Color(0, 204, 102));
        btnIzmeniStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeniStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeniStavku.setText("Измени селектовану ставку");
        btnIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuActionPerformed(evt);
            }
        });

        btnPrikaziStavku.setBackground(new java.awt.Color(0, 204, 102));
        btnPrikaziStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikaziStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikaziStavku.setText("Прикажи селектовану ставку");
        btnPrikaziStavku.setToolTipText("");
        btnPrikaziStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziStavkuActionPerformed(evt);
            }
        });

        lblDatumVremeKontrole1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDatumVremeKontrole1.setText("Датум контроле (дд.мм.гггг) :");

        txtVremeKontrole.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnObrisiStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnObrisiStavku.setForeground(new java.awt.Color(255, 0, 0));
        btnObrisiStavku.setText("Обриши селектовану ставку");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrTblStavke, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(btnDodajStavku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblDatumVremeKontrole1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPacijent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTerapija, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUkupnoVremeTrajanja)
                            .addComponent(txtVremeKontrole)
                            .addComponent(txtDatumKontrole)
                            .addComponent(txtDatumVremeZavrsetka)
                            .addComponent(cmbPacijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTerapija, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIdPregleda, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(lblLekar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLekar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKreirajPregled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdPregleda, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(btnObrisiStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreirajPregled)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumVremeKontrole1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatumVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVremeKontrole, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUkupnoVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTerapija, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(scrTblStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDodajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajPregled, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnObrisiStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikaziStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        lblIdPregleda.getAccessibleContext().setAccessibleName("200");
        lblLekar.getAccessibleContext().setAccessibleName("200");
        lblPacijent.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeKontrole.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeZavrsetka.getAccessibleContext().setAccessibleName("200");
        lblUkupnoVremeTrajanja.getAccessibleContext().setAccessibleName("200");
        lblTerapija.getAccessibleContext().setAccessibleName("200");
        lblDatumVremeKontrole1.getAccessibleContext().setAccessibleName("200");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajPregledActionPerformed

        try {
            Pregled pregledRez = (Pregled) GuiController.vratiInstancu().kreirajPregled(new Pregled());
            if (pregledRez != null) {
                txtIdPregleda.setText("" + pregledRez.getIdPregled());
                JOptionPane.showMessageDialog(this, "Успешно креиран Ид прегледа !",
                        "ОБАВЕШТЕЊЕ", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnKreirajPregledActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed

        StavkaPregleda stavka = new StavkaPregleda();

        // prikaz dialoga za stavku
        StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme, tblModel);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnSacuvajPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajPregledActionPerformed

        // provera da li su uneta neophodna polja
        if ("".equals(txtIdPregleda.getText()) || cmbLekar.getSelectedItem() == null
                || cmbPacijent.getSelectedItem() == null || "".equals(txtTerapija.getText())) {
            JOptionPane.showMessageDialog(this, "Нисте попунили неопходна поља! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tblModel.getStavke().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Немате ниједну ставку прегледа ! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // pokretanje izmene (update) koja je deo SK:Kreiraj pregled
        try {
            Pregled pregled = new Pregled();

            pregled.setIdPregled(Integer.parseInt(txtIdPregleda.getText()));
            pregled.setLekar((Lekar) cmbLekar.getSelectedItem());
            pregled.setPacijent((Pacijent) cmbPacijent.getSelectedItem());
            pregled.setDatumVremeZavrsetka(LocalDateTime.now());

            // datumKontrole i vremeKontrole
            DateTimeFormatter formaterDatum = DateTimeFormatter.ofPattern("dd.MM.yyyy['.']");
            DateTimeFormatter formaterVreme = DateTimeFormatter.ofPattern("HH:mm");
            LocalDate datumKontrole = LocalDate.parse(txtDatumKontrole.getText(), formaterDatum);
            LocalTime vremeKontrole = LocalTime.parse(txtVremeKontrole.getText(), formaterVreme);
            pregled.setDatumKontrole(datumKontrole);
            pregled.setVremeKontrole(vremeKontrole);

            // stavke pregleda
            List<StavkaPregleda> stavke = tblModel.getStavke();
            Duration ukupnoVremeTrajanja = Duration.ZERO;
            for (StavkaPregleda sp : stavke) {
                sp.setPregled(pregled);
                ukupnoVremeTrajanja = ukupnoVremeTrajanja.plus(sp.getVremeTrajanja());
            }

            // ukupno vreme trajanja
            pregled.setUkupnoVremeTrajanja(ukupnoVremeTrajanja);
            pregled.setStavke(stavke);
            GuiController.vratiInstancu().promeniPregled(pregled);

            // terapija
            pregled.setTerapija(txtTerapija.getText());
            
            
            JOptionPane.showMessageDialog(this, "Успешно чување прегледа !",
                    "ОБАВЕШТЕЊЕ", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом чувања прегледа !",
                    "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSacuvajPregledActionPerformed

    private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIzmeneActionPerformed

        // provera da li su uneta neophodna polja
        if (cmbLekar.getSelectedItem() == null || cmbPacijent.getSelectedItem() == null
                || "".equals(txtTerapija.getText()) || "".equals(txtDatumKontrole.getText())
                || "".equals(txtVremeKontrole.getText()) || "".equals(txtTerapija.getText())) {
            JOptionPane.showMessageDialog(this, "Нисте попунили неопходна поља! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Pregled pi = new Pregled();
        pi.setIdPregled(Integer.parseInt(txtIdPregleda.getText()));
        pi.setLekar((Lekar) cmbLekar.getSelectedItem());
        pi.setPacijent((Pacijent) cmbPacijent.getSelectedItem());
        pi.setDatumVremeZavrsetka(LocalDateTime.parse(txtDatumVremeZavrsetka.getText()));
        pi.setDatumKontrole(LocalDate.parse(txtDatumKontrole.getText()));
        pi.setVremeKontrole(LocalTime.parse(txtVremeKontrole.getText()));

        // ukupno vreme trajanja
        int minuti = Integer.parseInt(txtUkupnoVremeTrajanja.getText());
        Duration ukupnoVreme = Duration.ofMinutes(minuti);
        pi.setUkupnoVremeTrajanja(ukupnoVreme);
        // terapija
        pi.setTerapija("" + txtTerapija.getText());

        // uzimanje stavki
        List<StavkaPregleda> stavke = tblModel.getStavke();
        for (StavkaPregleda sp : stavke) {
            sp.setPregled(pi);
        }
        pi.setStavke(stavke);

        try {
            GuiController.vratiInstancu().promeniPregled(pi);
            JOptionPane.showMessageDialog(this, "Успешна измена прегледа ! ", "ОБАВЕШТЕЊЕ", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом измене прегледа ! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnSacuvajIzmeneActionPerformed

    private void btnIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuActionPerformed
        int selektovaniRed = tblStavkaPregleda.getSelectedRow();

        if (selektovaniRed != -1) {
            StavkaPregleda stavka = new StavkaPregleda();
            StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme, tblModel);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnIzmeniStavkuActionPerformed

    private void btnPrikaziStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziStavkuActionPerformed
        int selektovaniRed = tblStavkaPregleda.getSelectedRow();

        if (selektovaniRed != -1) {
            StavkaPregleda stavka = new StavkaPregleda();
            StavkaPregledaDialog dialog = new StavkaPregledaDialog(parent, true, stavka, modForme, tblModel);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziStavkuActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed

        int selektovaniRed = tblStavkaPregleda.getSelectedRow();
        if (selektovaniRed != -1) {
            int odgovor = JOptionPane.showConfirmDialog(
                    this,
                    "Да ли желите да обришете пацијента",
                    "БРИСАЊЕ",
                    JOptionPane.YES_NO_OPTION
            );
            if (odgovor == JOptionPane.YES_OPTION) {
                // brisanje pacijenta - sklanjanje iz tabela
                tblModel.izbrisiStavku(selektovaniRed);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали ставку прегледа !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    private void obradaModa() {

        if (modForme == ModForme.MOD_KREIRANJE) {
            lblNaslov.setText("КРЕИРАЊЕ ПРЕГЛЕДА");
            lblDatumVremeZavrsetka.setVisible(false);
            txtDatumVremeZavrsetka.setVisible(false);

            // sakrivanje dugmeta
            btnSacuvajIzmene.setVisible(false);
            btnIzmeniStavku.setVisible(false);
            btnPrikaziStavku.setVisible(false);

        } else if (modForme == ModForme.MOD_IZMENA) {
            lblNaslov.setText("ИЗМЕНА ПРЕГЛЕДА");
            lblDatumVremeZavrsetka.setVisible(false);
            txtDatumVremeZavrsetka.setVisible(false);
            lblIdPregleda.setVisible(false);
            txtIdPregleda.setVisible(false);

            // sakrivanje dugmeta
            btnKreirajPregled.setVisible(false);
            btnSacuvajPregled.setVisible(false);
            btnDodajStavku.setVisible(false);
            btnPrikaziStavku.setVisible(false);

            prikazPregleda();

        }
    }

    private void obradaCmbModela() {
        // za pacijenta
        List<Pacijent> pacijenti;
        try {
            pacijenti = GuiController.vratiInstancu().vratiSvePacijente();
            Pacijent[] nizPacijenti = new Pacijent[pacijenti.size()];
            nizPacijenti = pacijenti.toArray(nizPacijenti);
            DefaultComboBoxModel<Pacijent> modelP = new DefaultComboBoxModel<>(nizPacijenti);
            cmbPacijent.setModel(modelP);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања пацијената !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

        // za lekara
        List<Lekar> lekari;
        try {
            lekari = GuiController.vratiInstancu().vratiSveLekare();
            Lekar[] nizLekari = new Lekar[lekari.size()];
            nizLekari = lekari.toArray(nizLekari);
            DefaultComboBoxModel<Lekar> modelL = new DefaultComboBoxModel<>(nizLekari);
            cmbLekar.setModel(modelL);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања лекара !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }

    private void ucitajStavke() {

        List<StavkaPregleda> stavke;
        try {
            stavke = GuiController.vratiInstancu().vratiStavkeUslov(pregledGlobal);
            tblModel = new TblModelStavkaPregleda(stavke);
            tblStavkaPregleda.setModel(tblModel);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања ставки прегледа !",
                    "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }

    private void prikazPregleda() {

        txtIdPregleda.setText("" + pregledGlobal.getIdPregled());
        cmbLekar.setSelectedItem(pregledGlobal.getLekar());
        cmbPacijent.setSelectedItem(pregledGlobal.getPacijent());
        txtDatumVremeZavrsetka.setText("" + pregledGlobal.getDatumVremeZavrsetka());

        // datumKontrole i vremeKontrole kontrole
        txtDatumKontrole.setText("" + pregledGlobal.getDatumKontrole());
        txtVremeKontrole.setText("" + pregledGlobal.getVremeKontrole());
        // ukupno vreme trajanja
        txtUkupnoVremeTrajanja.setText(String.valueOf(pregledGlobal.getUkupnoVremeTrajanja().toMinutes()));
        txtTerapija.setText(pregledGlobal.getTerapija());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnIzmeniStavku;
    private javax.swing.JButton btnKreirajPregled;
    private javax.swing.JButton btnObrisiStavku;
    private javax.swing.JButton btnPrikaziStavku;
    private javax.swing.JButton btnSacuvajIzmene;
    private javax.swing.JButton btnSacuvajPregled;
    private javax.swing.JComboBox<Lekar> cmbLekar;
    private javax.swing.JComboBox<Pacijent> cmbPacijent;
    private javax.swing.JLabel lblDatumVremeKontrole;
    private javax.swing.JLabel lblDatumVremeKontrole1;
    private javax.swing.JLabel lblDatumVremeZavrsetka;
    private javax.swing.JLabel lblIdPregleda;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPacijent;
    private javax.swing.JLabel lblTerapija;
    private javax.swing.JLabel lblUkupnoVremeTrajanja;
    private javax.swing.JScrollPane scrTblStavke;
    private javax.swing.JTable tblStavkaPregleda;
    private javax.swing.JTextField txtDatumKontrole;
    private javax.swing.JTextField txtDatumVremeZavrsetka;
    private javax.swing.JTextField txtIdPregleda;
    private javax.swing.JTextField txtTerapija;
    private javax.swing.JTextField txtUkupnoVremeTrajanja;
    private javax.swing.JTextField txtVremeKontrole;
    // End of variables declaration//GEN-END:variables
}
