/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import controller.GuiController;
import domen.Dijagnoza;
import domen.Lekar;
import domen.Pacijent;
import domen.Pregled;
import gui.enumi.ModForme;
import gui.enumi.ModFormePretrazi;
import gui.komponente.TblModelPregled;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class PretragaPregledaDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PretragaPregledaDialog.class.getName());

    /**
     * Creates new form KreirajPregledDialog
     */
    private final java.awt.Frame parent;
    private final ModFormePretrazi modForme;
    private TblModelPregled model;

    public PretragaPregledaDialog(java.awt.Frame parent, boolean modal, ModFormePretrazi modForme) {
        super(parent, modal);
        initComponents();
        // postavljanje boje
        getContentPane().setBackground(Color.white);

        this.parent = parent;
        this.modForme = modForme;

        //funkcije
        obradaModa();
        obradaCmbModela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaslov = new javax.swing.JLabel();
        lblLekar = new javax.swing.JLabel();
        btnPretrazi = new javax.swing.JButton();
        lblDijagnoza = new javax.swing.JLabel();
        cmbLekar = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPregledi = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPrikazi = new javax.swing.JButton();
        lblPacijent = new javax.swing.JLabel();
        cmbPacijent = new javax.swing.JComboBox<>();
        cmbDijagnoza = new javax.swing.JComboBox<>();
        lblIdPregleda = new javax.swing.JLabel();
        txtDatumVremeZavrsetka = new javax.swing.JTextField();
        txtIdPregleda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ПРЕТРАГА ПРЕГЛЕДА");

        lblLekar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekar.setText("Избор лекара :");
        lblLekar.setPreferredSize(new java.awt.Dimension(170, 14));

        btnPretrazi.setBackground(new java.awt.Color(0, 153, 153));
        btnPretrazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPretrazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPretrazi.setText("Претражи");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        lblDijagnoza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDijagnoza.setText("Избор дијагнозе :");

        cmbLekar.setOpaque(true);
        cmbLekar.setPreferredSize(new java.awt.Dimension(300, 20));
        cmbLekar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLekarActionPerformed(evt);
            }
        });

        tblPregledi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ид ставке прегледа", "Лекар", "Пацијент", "Датум и време завршетка", "Датум и време контроле", "Укупно време трајња", "Терапија"
            }
        ));
        jScrollPane2.setViewportView(tblPregledi);

        btnIzmeni.setBackground(new java.awt.Color(0, 153, 153));
        btnIzmeni.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnIzmeni.setForeground(new java.awt.Color(255, 255, 255));
        btnIzmeni.setText("Измени селектовани преглед");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPrikazi.setBackground(new java.awt.Color(0, 153, 153));
        btnPrikazi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPrikazi.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikazi.setText("Прикажи селектовани преглед");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        lblPacijent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPacijent.setText("Избор пацијента :");
        lblPacijent.setPreferredSize(new java.awt.Dimension(170, 14));

        cmbPacijent.setOpaque(true);
        cmbPacijent.setPreferredSize(new java.awt.Dimension(300, 20));
        cmbPacijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPacijentActionPerformed(evt);
            }
        });

        cmbDijagnoza.setOpaque(true);
        cmbDijagnoza.setPreferredSize(new java.awt.Dimension(300, 20));
        cmbDijagnoza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDijagnozaActionPerformed(evt);
            }
        });

        lblIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdPregleda.setText("Ид прегледа :");
        lblIdPregleda.setPreferredSize(new java.awt.Dimension(170, 14));

        txtDatumVremeZavrsetka.setEditable(false);
        txtDatumVremeZavrsetka.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtIdPregleda.setEditable(false);
        txtIdPregleda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(409, 409, 409)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(732, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPacijent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLekar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPregleda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(240, 240, 240)
                    .addComponent(txtDatumVremeZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        cmbLekar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed

        Pregled pregledPr = new Pregled();
        // uzimanje uslova
        pregledPr.setIdPregled(Integer.parseInt(txtIdPregleda.getText()));
        pregledPr.setLekar((Lekar) cmbLekar.getSelectedItem());
        pregledPr.setPacijent((Pacijent) cmbPacijent.getSelectedItem());
        

    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed

        int selektovanRed = tblPregledi.getSelectedRow();
        if (selektovanRed != -1) {
            PregledDialog dialog = new PregledDialog(parent, true, new Pregled(), ModForme.MOD_IZMENA);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали преглед !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed

        int selektovaniRed = tblPregledi.getSelectedRow();
        if (selektovaniRed != -1) {
            // kreiranje pregleda
            Pregled pregled = model.getPregled(selektovaniRed);
            // forma 
            PregledDialog dialog = new PregledDialog(parent, true, pregled, ModForme.MOD_PRIKAZ);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Нисте селектовали преглед !", "УПОЗОРЕЊЕ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void cmbLekarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLekarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbLekarActionPerformed

    private void cmbPacijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPacijentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPacijentActionPerformed

    private void cmbDijagnozaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDijagnozaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDijagnozaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void obradaCmbModela() {

        // za lekara
        List<Lekar> lekari;
        try {
            lekari = GuiController.vratiInstancu().vratiSveLekare();
            Lekar[] nizLekari = new Lekar[lekari.size()];
            nizLekari = lekari.toArray(nizLekari);
            DefaultComboBoxModel<Lekar> modelL = new DefaultComboBoxModel<>(nizLekari);
            cmbLekar.setModel(modelL);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања лекара !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

        // za pacijente
        List<Pacijent> pacijenti;
        try {
            pacijenti = GuiController.vratiInstancu().vratiSvePacijente();
            Pacijent[] nizPacijenti = new Pacijent[pacijenti.size()];
            nizPacijenti = pacijenti.toArray(nizPacijenti);
            DefaultComboBoxModel<Pacijent> modelP = new DefaultComboBoxModel<>(nizPacijenti);
            cmbPacijent.setModel(modelP);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања пацијената !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

        // za dijagnozu
        List<Dijagnoza> dijagnoze;
        try {
            dijagnoze = GuiController.vratiInstancu().vratiSveDijagnoze();
            Dijagnoza[] nizDijagnoze = new Dijagnoza[dijagnoze.size()];
            nizDijagnoze = dijagnoze.toArray(nizDijagnoze);
            DefaultComboBoxModel<Dijagnoza> modelD = new DefaultComboBoxModel<>(nizDijagnoze);
            cmbDijagnoza.setModel(modelD);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Грешка приликом учитавања дијагноза !", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void obradaModa() {

        if (modForme == ModFormePretrazi.MOD_PRETRAZI_IZMENI) {
            lblNaslov.setText("ПРЕТРАГА И ИЗМЕНА ПРЕГЛЕДА");
            btnPrikazi.setVisible(false);
        } else if (modForme == ModFormePretrazi.MOD_PRETRAZI_PRIKAZI) {
            lblNaslov.setText("ПРЕТРАГА И ПРИКАЗ ПРЕГЛЕДА");
            btnIzmeni.setVisible(false);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<Dijagnoza> cmbDijagnoza;
    private javax.swing.JComboBox<Lekar> cmbLekar;
    private javax.swing.JComboBox<Pacijent> cmbPacijent;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDijagnoza;
    private javax.swing.JLabel lblIdPregleda;
    private javax.swing.JLabel lblLekar;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblPacijent;
    private javax.swing.JTable tblPregledi;
    private javax.swing.JTextField txtDatumVremeZavrsetka;
    private javax.swing.JTextField txtIdPregleda;
    // End of variables declaration//GEN-END:variables
}
