/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.forme.pregled;

import domen.Dijagnoza;
import domen.StavkaPregleda;
import gui.enumi.ModForme;
import gui.komponente.TblModelStavkaPregleda;
import gui.pomocni.Pomocni;
import java.awt.Color;
import java.time.Duration;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aleksandar Čeganjac
 */
public class StavkaPregledaDialog extends javax.swing.JDialog {

    /**
     * Creates new form KreirajPregledDialog
     */
    private final StavkaPregleda stavkaPregleda;
    private final ModForme modForme;
    TblModelStavkaPregleda tblModel;

    public StavkaPregledaDialog(java.awt.Frame parent, boolean modal, StavkaPregleda stavkaPregleda,
            ModForme modForme, TblModelStavkaPregleda tblModel) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
        this.stavkaPregleda = stavkaPregleda;
        this.modForme = modForme;
        this.tblModel = tblModel;
        obradaModa();
        obradaCmbDijagnoza();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblNaslov = new javax.swing.JLabel();
        lblIdStavke = new javax.swing.JLabel();
        txtIdStavke = new javax.swing.JTextField();
        lblDijagnoza = new javax.swing.JLabel();
        cmbDijagnoza = new javax.swing.JComboBox<>();
        btnSacuvajStavku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLekarskiNalaz = new javax.swing.JTextArea();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblVremeTrajanja = new javax.swing.JLabel();
        txtVremeTrajanja = new javax.swing.JTextField();
        lblLekarskiNalaz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblNaslov.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNaslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNaslov.setText("ДОДАВАЊЕ СТАВКЕ ПРЕГЛЕДА");

        lblIdStavke.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIdStavke.setText("Ид ставке :");
        lblIdStavke.setPreferredSize(new java.awt.Dimension(80, 20));

        txtIdStavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdStavkeActionPerformed(evt);
            }
        });

        lblDijagnoza.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDijagnoza.setText("Дијагноза :");

        btnSacuvajStavku.setBackground(new java.awt.Color(0, 153, 153));
        btnSacuvajStavku.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSacuvajStavku.setForeground(new java.awt.Color(255, 255, 255));
        btnSacuvajStavku.setText("Сачувај ставку прегледа");
        btnSacuvajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajStavkuActionPerformed(evt);
            }
        });

        txaLekarskiNalaz.setColumns(20);
        txaLekarskiNalaz.setRows(5);
        txaLekarskiNalaz.setPreferredSize(new java.awt.Dimension(240, 80));
        jScrollPane1.setViewportView(txaLekarskiNalaz);

        lblNaziv.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNaziv.setText("Назив :");
        lblNaziv.setPreferredSize(new java.awt.Dimension(80, 20));

        txtNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivActionPerformed(evt);
            }
        });

        lblVremeTrajanja.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblVremeTrajanja.setText("Време трајања :");
        lblVremeTrajanja.setPreferredSize(new java.awt.Dimension(80, 20));

        txtVremeTrajanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVremeTrajanjaActionPerformed(evt);
            }
        });

        lblLekarskiNalaz.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLekarskiNalaz.setText("Лекарски налаз :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNaslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvajStavku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLekarskiNalaz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDijagnoza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(txtIdStavke)
                            .addComponent(txtVremeTrajanja, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(cmbDijagnoza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblNaslov, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdStavke, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblIdStavke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblVremeTrajanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDijagnoza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLekarskiNalaz, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnSacuvajStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajStavkuActionPerformed

        if ("".equals(txtNaziv.getText()) || "".equals(txtVremeTrajanja.getText())
                || cmbDijagnoza.getSelectedItem() == null || "".equals(txaLekarskiNalaz.getText())) {
            JOptionPane.showMessageDialog(this, "Нисте попунили неопходна поља! ", "ГРЕШКА", JOptionPane.ERROR_MESSAGE);
            return;
        }

        StavkaPregleda stavka = new StavkaPregleda();

        // uzimanje podataka iz polja
        stavka.setNaziv(txtNaziv.getText());
        // trajanje
        int trajanjeInt = Integer.parseInt(txtVremeTrajanja.getText());
        Duration trajanjeD = Duration.ofMinutes(trajanjeInt);
        stavka.setVremeTrajanja(trajanjeD);

        stavka.setDijagnoza((Dijagnoza) cmbDijagnoza.getSelectedItem());
        stavka.setLekarskiNalaz(txaLekarskiNalaz.getText());

        tblModel.dodajStavku(stavka);


    }//GEN-LAST:event_btnSacuvajStavkuActionPerformed

    private void txtIdStavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdStavkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdStavkeActionPerformed

    private void txtNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivActionPerformed

    private void txtVremeTrajanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVremeTrajanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVremeTrajanjaActionPerformed

    // obrada moda forme
    private void obradaModa() {

        if (modForme == modForme.MOD_KREIRANJE) {
            lblIdStavke.setVisible(false);
            txtIdStavke.setVisible(false);
        } else if (modForme == modForme.MOD_IZMENA) {
            lblNaslov.setText("ИЗМЕНА СТАВКЕ ПРЕГЛЕДА");
            txtIdStavke.setEditable(false);
            btnSacuvajStavku.setText("Сачувај измене");
        } else if (modForme == modForme.MOD_PRIKAZ) {
            lblNaslov.setText("ПРИКАЗ СТАВКЕ ПРЕГЛЕДА");
            btnSacuvajStavku.setVisible(false);
            txtIdStavke.setEditable(false);
            txtNaziv.setEditable(false);
            txtVremeTrajanja.setEditable(false);
            txaLekarskiNalaz.setEditable(false);
            cmbDijagnoza.setEnabled(false);
            txaLekarskiNalaz.setEditable(false);
        }

    }

    // obrada cmbDijagnoza
    private void obradaCmbDijagnoza() {
        List<Dijagnoza> dijagnoze = Pomocni.vratiDijagnoze();
        Dijagnoza[] nizDijagnoze = new Dijagnoza[dijagnoze.size()];
        nizDijagnoze = dijagnoze.toArray(nizDijagnoze);
        DefaultComboBoxModel<Dijagnoza> modelD = new DefaultComboBoxModel<>(nizDijagnoze);
        cmbDijagnoza.setModel(modelD);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvajStavku;
    private javax.swing.JComboBox<Dijagnoza> cmbDijagnoza;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDijagnoza;
    private javax.swing.JLabel lblIdStavke;
    private javax.swing.JLabel lblLekarskiNalaz;
    private javax.swing.JLabel lblNaslov;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblVremeTrajanja;
    private javax.swing.JTextArea txaLekarskiNalaz;
    private javax.swing.JTextField txtIdStavke;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtVremeTrajanja;
    // End of variables declaration//GEN-END:variables
}
